### ISSUE TITLE
Exon UTR rendering error

### ISSUE THREAD

**Issue by imedina** [opencb/jsorolla#12]
When rendering the transcript ENST00000382387 with just 1 exon :

http://wwwdev.ebi.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/gene/ENST00000382387/info?exclude=transcripts.exons

When browsing in Genome Maps we can see that the exon is not correct rendered since the UTRs are not shown:

http://bioinfo.cipf.es/apps-beta/genome-maps/beta/?CELLBASE_HOST=https://wwwdev.ebi.ac.uk/cellbase/webservices/rest

**Comment by imedina** [comment]
What's the status of this issue?

**Comment by imedina** [comment]
Maybe related, the white exon of transcript ENST00000584751 at region 22:18293414-18293568 should be red, like in:

http://grch37.ensembl.org/Homo_sapiens/Location/View?r=22:18293492-18293509

**Comment by agaor** [comment]
> Maybe related, the white exon of transcript ENST00000584751 at region 22:18293414-18293568 should be red, like in:http://grch37.ensembl.org/Homo_sapiens/Location/View?r=22:18293492-18293509

The transcript is now red.
