### ISSUE TITLE
QueryResult is now always a List in CellBase

### ISSUE THREAD

**Issue by imedina** [opencb/jsorolla#14]
CellBase has integrated OpenCB Datastore library so new QueryResult objects is used. For sanity all 'result' return objects are now **always** a List, no objects are returned any more like in:

http://wwwdev.ebi.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/chromosome/13/info?of=json 

This makes client JS apps such as Genome Maps and Cell Maps to fail for some web services.

New QueryResult object is:

https://github.com/opencb/datastore/blob/develop/datastore-core/src/main/java/org/opencb/datastore/core/QueryResult.java#L19

**Comment by frasator** [comment]
Updated some CellBase web service responses, but some CellBase urls like:
http://localhost:8080/cellbase/webservices/rest/v3/hsapiens/genomic/region/13:32800000-32899999/gene?exclude=transcripts&of=json

are returning null using CellBase  feature/datastore  and datastore feature/next and the example dataset from https://www.dropbox.com/sh/itd1j9mvjegggaa/AABHvmZP4BTrMzUXtv0syQaUa?dl=0
on a fresh CellBase installation, maybe I forgot something?

**Comment by imedina** [comment]
Not all WS have been ported, they should be ready for the end of week
