### ISSUE TITLE
Where is style.css maintained and how does is it end up genome maps?

### ISSUE THREAD

**Issue by alyh** [opencb/jsorolla#15]
Genome maps contains text formatting classes in style.css which has a very similar copy here:
https://github.com/opencb/jsorolla/blob/master/styles/css/style.css#L1051

When is this added to genome maps? 
I don't see the file in https://github.com/opencb/genome-maps

Also shouldn't there be a prefix for these class names so there aren't conflicts elsewhere?

**Comment by frasator** [comment]
It is here:
https://github.com/opencb/genome-maps/blob/develop/src/genome-maps.html#L33

Yes, that classes should not be used anymore.
