### ISSUE TITLE
Race condition in ajax function in Bootstrap Table

### ISSUE THREAD

**Issue by antonioaltamura** [opencb/jsorolla#153]
**Describe the bug**
All Bootstrap Tables can reach an inconsistent state in case you perform two queries one right after the other, and the first request is slower. As soon as both requests are fulfilled, the table shows the results of the slower query, while the pagination information sticks with the faster query.

**To Reproduce**
- go to Variant Browser
- select a variant X with many samples, and go to the Sample tab (`opencga-variant-samples`)
- select 100 entries per page (this is just for launching a query that takes time)
- select another variant Y (the first request is still pending)
- the Sample tab will show the samples of the variant Y
- once the first query is completed, the table will show the samples of the variant X, but the pagination info (including the total number of samples) of variant Y

Example: the first request with a delay of 10 seconds returns 5 results, the second request with a delay of 1 second returns 3 results.

https://user-images.githubusercontent.com/6325475/121604748-5d345200-ca4b-11eb-8514-6228b364f097.mp4

**Comment by imedina** [comment]
@antonioaltamura is this issue ready to be closed?

**Comment by antonioaltamura** [comment]
@imedina Yes
