### ISSUE TITLE
Change hosts to host in CellbaseClient

### ISSUE THREAD

**Issue by agaor** [opencb/jsorolla#162]
Currently the CellbaseClient configuration has several hots. It is required to switch to a single host as multiple hosts will not be used and to unify the entire repository.

**Comment by antonioaltamura** [comment]
Hi @agaor. Soon the Cellbase host URL will be provided by Opencga therefore it will be removed from the configuration.

**Comment by agaor** [comment]
All services are verified to function properly with this change. The task is closed.
