### ISSUE TITLE
Consolidate web components for some HTML controls

### ISSUE THREAD

**Issue by imedina** [opencb/jsorolla#165]
It would be great to consolidate and improve some commons web components controls in JSorolla, this is the current situation:

| Functionality | Component                        | Dependency          |
|---------------|----------------------------------|---------------------|
| Dropdown      | select-field-filter              | bootstrap-select    |
| Autocomplete  | select-field-filter-autocomplete | bootstrap3-typeahead |
| Token/Tag     | select-field-token               | tokenize            |

And the proposed plan would be:

| Functionality | Component            | Dependency       |
|---------------|----------------------|------------------|
| Dropdown      | select-control       | bootstrap-select |
| Autocomplete  | autocomplete-control | select2          |
| Token/Tag (autocomplete)     | token-control        | select2          |
| Token/Tag (free-input)    | token-control-static        | select2          |

**Comment by antonioaltamura** [comment]
It seems you can easily reach an inconsistent state when you use canned filters.
![OpenCGA-Suite (1)](https://user-images.githubusercontent.com/6325475/134035276-30171456-2b36-4322-86d2-00b54f13f07a.png)

**Comment by antonioaltamura** [comment]
> It seems you can easily reach an inconsistent state when you use canned filters.
> [<img src="https://user-images.githubusercontent.com/6325475/134035276-30171456-2b36-4322-86d2-00b54f13f07a.png" width="250"/>](https://user-images.githubusercontent.com/6325475/134035276-30171456-2b36-4322-86d2-00b54f13f07a.png)




Commit https://github.com/opencb/jsorolla/commit/45ae0d06345026d0a363e6693a7e7bc082491a25#diff-1a2dd026d95821be7110d05dcf67361b02086dd907725f5fefd612ac1a40b2de has fixed this issue.
