### ISSUE TITLE
jso-opencga-header web component

### ISSUE THREAD

**Issue by pfurio** [opencb/jsorolla#17]
The web component does not hide attributes such as the login/sign up buttons when required. 

Polymer 1.0 documentation says that boolean properties are set based on the existence of the attribute: if the attribute exists at all, its value is true, regardless of its string-value (and the value is only false if the attribute does not exist). Therefore, all boolean properties of every Polymer element have to be set to false by default (and not true) and have to be explicitly declared to activate them. 

Below, the way it should be:

```
allowLogin: {
                type: Boolean,
                value: false,
                reflectToAttribute: true
},
```

**Comment by agaor** [comment]
The code has changed and this issue is already fixed.
