### ISSUE TITLE
IVA: get CellBase configuration from project

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#173]
At this moment, we have a fixed CellBase host and version in IVA config: 

```js
const cellbase = {
    host: "https://ws.opencb.org/cellbase-4.8.2",
    version: "v4"
};
```

But in OpenCGA v2, each project has his own CellBase version and host. So instead of having a fixed CellBase configured in IVA, we need to get the CellBase configuration from the current project. Each project has a `internal` object with a `cellbase` field that contains the host and version used on all studies of this project. This information is accesible in the `opencgaSession` object: 

![image](https://user-images.githubusercontent.com/5751201/133980315-e4c5c293-e1d4-45b6-a33b-3d97b77756d5.png)

Note that the `project` field is a reference to the active project. Each time we change the current project we will need to create a new CellBase client instance using the CellBase configuration of the new project.

**Comment by jmjuanes** [comment]
Created a function `updateCellBaseClient` for updating the cellbase client with the current active project configuration (if exists): 

https://github.com/opencb/jsorolla/blob/7663ef5122f6ce16a9057747e19c50ba3015b79e/src/sites/iva/iva-app.js#L757-L766

This function is called after fetching the projects of the user or when the active study changes.

**Comment by pamag** [comment]
@antonioaltamura Please could you test this fix in your environment?

**Comment by antonioaltamura** [comment]
@pamag Yes, https://github.com/opencb/jsorolla/commit/5f9f6f761ffe57ffac9ad8be867e463ec72301bf fixed the issue for me.
