### ISSUE TITLE
Admin: Clinical and Variants Configurations

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#183]
Currently, the administration interface does not have clinical and variant configurations.

We need to implement it, which will allow the administrator user to configure Clinical or Variants directly from the web

**Main Component for configs**
- [x] Create a Clinical Config Component
- [x] Create a Variant Engine Config Component

**Features for clinical  (add, edit, remove)**
- [x]  Status 
- [x]  Interpretation
- [x]  priorities
- [x]  flags
- [x] consent

**Features for variant configs (add, edit, remove)**
- [x] File Index Configuration (Custom Fields)
- [x] Annotation index Configuration

**Comment by pamag** [comment]
## Reviewed
commit:  f104bd4712825f4c4fdc278c088a4b7b7bff1bf0

CREATED CONFIGURATIONS


Closed with some issues addressed in new issues:

-- Still, the new values are not saved in the database. -> 
The changes are transient: it gives the impression that can be used if we change to case manager

![image](https://user-images.githubusercontent.com/167875/150717631-431c602c-64d2-461f-b241-0f53c5b4545a.png)

 but if we refresh the browser, the changes are lost.
![image](https://user-images.githubusercontent.com/167875/150717729-d3425f4d-699d-4cee-9e12-d4e1111b6ae7.png)

see #361 and #362
