### ISSUE TITLE
Admin: Clean up & review admin interface components 

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#194]
At the moment, Admin does not contain its own folder for all the components that compose it. 

**TO DO**
- [x] A folder will be created for all parts of admin.
- [x] Each component of the admin will be cleaned and reviewed. (remove unused code and comments)
- [x] Maintain code consistency  * -create,  * -update,  * -view

**Comment by Rodielm** [comment]
At the moment, improvements have been made to each component part of the admin interface. 

To ensure the functionality of each part of the admin, new issues will be created for each part of the admin interface.

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        58c76ae9a5
    IVA commit:
        a100ebd81423c38600013acd98a51e14a7b51309

DONE
