### ISSUE TITLE
Inconsistent values in the phenotypes column of the Individual Browser

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#204]
In the phenotypes column, there are some rows that displays a `X terms found` text, but in other rows displays some phenotypes:

![image](https://user-images.githubusercontent.com/5751201/138484906-4857e453-34a5-43f7-96c8-068170f22bc8.png)

**Comment by jmjuanes** [comment]
Problem found in tooltip content of the Phenotypes column: there are some phenotypes names that have HTML characters that breaks the `tooltip=''` attribute:

![image](https://user-images.githubusercontent.com/5751201/148752947-040984f9-e6c7-4b63-b9b8-7810c6bbb048.png)

We need to implement a utility to encode HTML characters (`<`, `>`, `&`, `'` and `"` characters) from unsafe strings:

```javascript
UtilsNew.escapeHtml("RAYNAUD'S PHENOMENON - MEDDRA:10037912");
// "RAYNAUD&#039;S PHENOMENON - MEDDRA:10037912"
```

**Comment by jmjuanes** [comment]
Problem found in tooltip content of the Phenotypes column: there are some phenotypes names that have HTML characters that breaks the `tooltip=''` attribute:

![image](https://user-images.githubusercontent.com/5751201/148754104-463fa8e6-4671-4653-8a1e-3256c37d4eba.png)

We need to implement a utility to encode HTML characters (`<`, `>`, `&`, `'` and `"` characters) from unsafe strings:

```javascript
UtilsNew.escapeHtml("RAYNAUD'S PHENOMENON - MEDDRA:10037912");
// "RAYNAUD&#039;S PHENOMENON - MEDDRA:10037912"
```

**Comment by jmjuanes** [comment]
Implemented the `UtilsNew.escapeHtml` utility in commit 3a0d209 and escape HTML characters in the phenotype name in commit 49a336d:

![image](https://user-images.githubusercontent.com/5751201/148754343-7331a703-8d09-403f-98c2-7ef25685de07.png)

Content in the tooltip is correctly encoded: 

![image](https://user-images.githubusercontent.com/5751201/148754545-4d7705fc-27d1-4cb1-817d-a102945b769c.png)

**Comment by pamag** [comment]
## Reviewed

FIXED
