### ISSUE TITLE
Allow intersect between regions

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#205]
**Is your feature request related to a problem? Please describe.**
In clinical settings where the search should be restricted to panels or when we have two lists of regions with features, it is important to be able to do an INTERSECT.

**Describe the solution you'd like**
We want the result of a intersection with b in the figure:
![image](https://user-images.githubusercontent.com/167875/138657031-b6416729-8d56-4fc6-a5e3-b6950f7f27ee.png)

The regions, genes and panels are an OR but we would need to have an option for INTERSECT

**NOTE**: this ticket needs coordination with OpenCGA developers.

**Comment by jmjuanes** [comment]
Added new parameter in OpenCGA to allow panel intersect with query elements (from Gene, Region and Xref): 
- Endpoint: `GET /{apiVersion}/analysis/variant/query`.
- Parameter: `panelIntersect = true/false`.

Related issue: opencb/opencga#1847

**Comment by jmjuanes** [comment]
Added panel intersection to Variant Browser in issue #274:

![image](https://user-images.githubusercontent.com/5751201/144024843-6436c0ee-7600-4db0-bf80-76f01cd3c20c.png)

**Comment by pamag** [comment]
## Reviewed

commit: f104bd4712825f4c4fdc278c088a4b7b7bff1bf0

FIXED
