### ISSUE TITLE
[feat] Add sample form in the sample-browser

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#206]
**Feature** 

Allow a sample form to update or modify information in the sample browser when the user selects a sample.

 **Why this feature?** 

Because the user has to navigate through 2 or 3 pages to edit the information of a specific sample. And with this feature the user can edit the sample within the sample browser without having to navigate elsewhere.

**Comment by pamag** [comment]
## Reviewed

**OK**

**Comment by pamag** [comment]
## Reviewed

**OK** but extended with two tickets

* https://github.com/opencb/jsorolla/issues/325
* https://github.com/opencb/jsorolla/issues/326
