### ISSUE TITLE
issue in case creation: if a sample/family is removed from the input area, still is kept in the sample/members display

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#208]
**Describe the bug**

![image](https://user-images.githubusercontent.com/167875/138693290-780129c9-ac0f-45b9-96e6-7fe22c30d1d4.png)

**To Reproduce**
1-- new case in case portal (http://localhost:9990/iva/#clinical-analysis-writer/)
![image](https://user-images.githubusercontent.com/167875/138693423-ba6c2764-7bc2-4718-b335-6f9858180356.png)

2-- select a proband
![image](https://user-images.githubusercontent.com/167875/138693489-fbc35f1b-038b-4b0a-9fd0-b3fb4fdb580d.png)
3-- remove the proband
![image](https://user-images.githubusercontent.com/167875/138693604-4cfdfe87-a445-4d41-9de2-adc2df7a2165.png)

 -----
same happens with family:
![image](https://user-images.githubusercontent.com/167875/138695851-0717e7d8-7de8-4a23-8618-e905e3107e1b.png)

**Note**
Despite having removed a family or proband, it is reatained 
![image](https://user-images.githubusercontent.com/167875/138694963-1cd4fc53-fe37-4bd2-9e20-e0dbfa2b99a9.png)

and the case is created if press in OK
![image](https://user-images.githubusercontent.com/167875/138695297-2ab144ea-737c-4f2b-909c-e9cc94f7a683.png)

**Comment by jmjuanes** [comment]
Fixed for **SINGLE** type in previous commit f113c8758539a63e496e7b313c27cc660dcbcac7, and for **FAMILY** and **CANCER** in commits 58b023e and ffe8b2e. The main idea is to destroy the saved proband data in the new clinical analysis object when the user removes the proband ID: 

https://github.com/opencb/jsorolla/blob/ffe8b2e2848148b686e2aade147b79652ab0cc8c/src/webcomponents/clinical/clinical-analysis-create.js#L199-L204

Now working as expected:

![Peek 2022-01-04 16-16](https://user-images.githubusercontent.com/5751201/148080932-87af9936-196c-47d2-976e-481619feb8b5.gif)

**Comment by pamag** [comment]
## Revied
commit: ffe8b2e2848148b686e2aade147b79652ab0cc8c 

**OK**
