### ISSUE TITLE
File selector web component

### ISSUE THREAD

**Issue by pfurio** [opencb/jsorolla#21]
Hi,

I think that would be interesting creating a component that will be just used for sample selection. I've drawn what to my understanding would be necessary.

![img_20160226_172107](https://cloud.githubusercontent.com/assets/4201841/13359687/64dde23c-dcad-11e5-9246-85942efa6da6.jpg)

The input that the component would receive is:
- The study from where the user wants to extract the data.
- Data formats we are going to allow for listing (bam, sam, vcf, fastq...)

The output will be an array of sample objects.

Ideally, in order to make this component work with anything, we should give as input a callback function. This way, this could work not only in OpenCGA but in other projects. However, a think that we could do a first version with just the input and output I said before.
### DESCRIPTION

Component 1 is a tree that will list all the directories created in the current study (ONLY THE DIRECTORIES). Once you select a directory, data from component 2 will be obtained. Component 2 will list all the samples of the format specified in the general component, that can be found in the selected directory searching recursively (it will look into all children directories). 

In component 2 we will be able to select the samples we want. The total number of selected samples as well as their names will be listed in (3).
### Justification

I think it is important being able to select many samples or files in general for many cases. I believe this way could be really simple for users to use allowing them to select many in just a few clicks.

I have already started creating the auxiliar webcomponents to create this, but I would like to know what you think of this. Do you find it interesting? Would you change/add/remove anything?

Thanks.

**Comment by agaor** [comment]
this issue is already resolved
