### ISSUE TITLE
Implement new web components to Create and Update Clinical Analysis

### ISSUE THREAD

**Issue by imedina** [opencb/jsorolla#212]
### Current situation
There are two components for the creation and update of cases:

1. `opencga-clinical-analysis-writer`: allows to _create_ and _update_ cases in a single component
2. `clinical-analysis-editor`: allows to edit cases 

### Plan
We must implement two different components called:

- [x] clinical-analysis-create: allows the creation of cases
- [x] clinical-analysis-update: to edit case information

**Comment by Rodielm** [comment]
There were 2 components

- `opencga-clinical-analysis-writer`: with the two responsibilities to create and edit cases.
- `clinical-analysis-editor`: with one responsibility to edit cases.

- One component has been created per responsibility, such as create and update cases just to simplify its use and the development of the same component in case some additional features are required according to its responsibility.

**Create Case - clinical-analysis-create**
![image](https://user-images.githubusercontent.com/10471758/151964273-10af117e-59c4-46a0-9cb8-42db85687af7.png)

**Edit Case - clinical-analisys-update**
![image](https://user-images.githubusercontent.com/10471758/151964461-0342e40e-70f8-4d17-a21f-f9cc68a57d91.png)

**Comment by pamag** [comment]
@imedina please can you review this ticket?

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        4947bd62b3bed373d7adac94c45d365bdce59c56
    IVA commit:
        5c977089ff901105e67c92157eac77f31afd8970
