### ISSUE TITLE
[iva] disease panels in create case in case_portal needs to be sorted and have autocompletion

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#215]
Disease panels list in `create case`: this needs to be sorted alfanumeric and the selected diseases needs to be displayed as badges
![image](https://user-images.githubusercontent.com/167875/139115124-c031cae9-5629-4d68-af16-75956875ac1b.png)

**Comment by imedina** [comment]
@pamag this should be fixed, can you review it?

**Comment by pamag** [comment]
![create-case_disease_panels](https://user-images.githubusercontent.com/167875/142561240-aba51d3e-14cd-4323-8cf6-53d44f99d1db.gif)
