### ISSUE TITLE
Bug: onerror handler references non-existing variable

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/jsorolla#22]
[indexedDB-store.js#L439](https://github.com/opencb/jsorolla/blob/develop/src/lib/cache/indexedDB-store.js#L439):

```
            transaction.onerror = function (event) {
                console.log("There was an error in the transaction put(" + key + ", ", value, ")");
                console.log(event);
            };

```

but there's no `key` or `value` variables defined in the `putall` method, it was probably copy/pasted from the `put` method.

**Comment by agaor** [comment]
Fixed. Thanks for your comment.
