### ISSUE TITLE
Case Interpreter: detail tabs are all displayed as active in the Interpretation Review

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#222]
The **General** tab remains as active when we enter in the **Primary Findings** tab of the **Interpretation Review**:

![image](https://user-images.githubusercontent.com/5751201/139424936-7c1975cd-705c-4ce0-9580-f263a7d52565.png)

Live preview of this bug:

![Peek 2021-10-29 13-56](https://user-images.githubusercontent.com/5751201/139430381-508efcc3-0aa3-4dd7-ab6c-21a344898997.gif)

**Comment by jmjuanes** [comment]
Switched to `detail-tabs` component for tabs managing. Now it works as expected:

![image](https://user-images.githubusercontent.com/5751201/139836897-82645ff7-4c69-451a-9a65-dbd62973d7ea.png)

![image](https://user-images.githubusercontent.com/5751201/139836949-61facbc0-5d07-45e8-9e38-87e849523fd7.png)

**Comment by imedina** [comment]
@jmjuanes this works fine now :-)   But I have just realized that the style has also improved (bold font), but this style improvement has not been propagated to the other tabs.

**Comment by jmjuanes** [comment]
> @jmjuanes this works fine now :-) But I have just realized that the style has also improved (bold font), but this style improvement has not been propagated to the other tabs. 

@imedina Yes, that is because other tabs are not using the `detail-tabs` component yet. I have created issue #259 to migrate to `detail-tabs` in all steps.

**Comment by pamag** [comment]
## Reviewed
OK
