### ISSUE TITLE
Case Interpreter: change Clinical tab of the Case Info Manager section

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#223]
## Description

At this moment the same component is displayed in the **Clinical** and the **Case Overview** tabs of the Case Info Manager section.

Example of the current **Clinical** tab:

![image](https://user-images.githubusercontent.com/5751201/139431443-cbc8c500-b0a5-41d4-b2c9-7955fbd94a8f.png)

Example of the current **Case Overview** tab: 

![image](https://user-images.githubusercontent.com/5751201/139431614-259ba619-7ace-4387-a353-f42410b9fbe8.png)

## Proposed solution

Change the **Clinical** tab to use the `individual-view` component.

**Comment by jmjuanes** [comment]
Solved in commit https://github.com/opencb/jsorolla/commit/d551f69955e959a99cbcaf8e1dd89bf1850ac972. Now using the `individual-view` component in the content of the **Clinical** tab: 

![image](https://user-images.githubusercontent.com/5751201/139841331-3944d227-55e3-4da2-88da-6299a570a5f7.png)

**Comment by pamag** [comment]
## Reviewed
OK
