### ISSUE TITLE
Case Interpreter: disable merge button 

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#224]
## Description 

At this moment, clicking in the **Merge** option of the actions dropdown do not trigger any action:

![image](https://user-images.githubusercontent.com/5751201/139445919-d075ecfa-a335-4711-b946-08e5f443e963.png)

## Proposed solution

We suggest disabling this action because it is not yet implemented.

**Comment by jmjuanes** [comment]
Implemented in commit https://github.com/opencb/jsorolla/commit/056e066085422154d1049b4e48385373377b98fa : 

![image](https://user-images.githubusercontent.com/5751201/139865723-f668efe0-7f24-476c-ab84-2906507a6238.png)

**Comment by imedina** [comment]
@jmjuanes @pamag following latest discussions I think it would better to remove the `Merge` options since it is no going to be needed anymore

**Comment by jmjuanes** [comment]
The merge action was removed from dropdown menu in commits 254307a and 13d782b : 

![image](https://user-images.githubusercontent.com/5751201/144256331-7c144711-7971-406c-a164-e492e624da76.png)

**Comment by pamag** [comment]
review and closed
