### ISSUE TITLE
Cohort Browser, Samples tab not rendering correctly

### ISSUE THREAD

**Issue by imedina** [opencb/jsorolla#225]
**Describe the bug**
The Samples tab in the Cohort Browser is returning a meaningless (to me) string rather than interpretable content

**To Reproduce**
Go to http://bioinfo.hpc.cam.ac.uk/web-apps/iva-prod/#cohort, Cohort Browser for 15k Genomes study, and click the Samples tab under the main grid. 

**Expected behavior**
I expect to see information on the Samples in the cohort.

**Screenshots**
![CleanShot 2021-10-27 at 16 20 38@2x](https://user-images.githubusercontent.com/64658139/139097477-d5d5fd16-d4e2-4f90-83e3-07539ebeb03f.png)

FYI @pamag , @sg550, @reshma23

**Comment by pamag** [comment]
related: #221

**Comment by pamagz** [comment]
This happens because we are not using a grid component that comes with pagination.
**ACTION** reformat this component and use a grid.
