### ISSUE TITLE
Redesign welcome page

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#227]
## Description

In the welcome app we are displaying the list of categories: 

![image](https://user-images.githubusercontent.com/5751201/140051558-f70b82c9-a442-4b73-811d-244cfce144cb.png)

Some of the items displayed on this welcome page redirect to a page where all tools in this category are displayed: 

![image](https://user-images.githubusercontent.com/5751201/140051849-9bb23751-c71c-4728-b31a-1a16b13e469f.png)

This is sometimes confusing for the user. Also, the items listed on the welcome page do not have a short description...

## Proposed solution

Redesign the welcome page to display the tools marked with a `featured` flag in the configuration, along with a description and a button to open the tool.

**Comment by jmjuanes** [comment]
First implementation of the new welcome page: 

![image](https://user-images.githubusercontent.com/5751201/140304101-50a173cf-31cf-4d33-916a-40d1e868e1ef.png)

**Comment by jmjuanes** [comment]
Finished development:

- Implemented new featured tools section in the welcome page (commits 70b9a50 and 0208ea7) 

![image](https://user-images.githubusercontent.com/5751201/140373451-23dc45c0-6392-43d7-b21d-256fcb731f9f.png)

- Disabled category links in the menu dropdown (commit fae4fa2).

![image](https://user-images.githubusercontent.com/5751201/140374613-b307e4dc-2cce-4fc8-bfab-78a74b09685d.png)

- Moved `category-page` component to `obsolete` folder (commit fc7d548).

**Comment by pamag** [comment]
## Reviewed

commit: f104bd4712825f4c4fdc278c088a4b7b7bff1bf0

FIXED
