### ISSUE TITLE
Dependency upgrade needed GRUNT-CONTRIB-QUNIT

### ISSUE THREAD

**Issue by jcortell** [opencb/jsorolla#23]
~0.2.2
REQUESTED
1.1.0
LATEST STABLE
10
RELEASES BEHIND

Risky upgrade: Take caution in upgrading this dependency as it may have breaking changes in its latest release.

How behind is this version?
1 BREAKING RELEASE
6 FEATURE RELEASES
3 PATCH RELEASES

NESTED SECURITY ADVISORY
semver Regular Expression Denial of Service
Discovered in a nested dependency:grunt-contrib-qunit@0.2.2grunt-lib-phantomjs@0.3.1semver@1.0.14

**Comment by agaor** [comment]
Thank you very much for your contribution.
Now grunt is removed from the Jsorolla project. Only npm is available.
