### ISSUE TITLE
ERROR when selecting an "interpretation Flag" in Case creation

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#231]
Several errors found in Case Create:

## Description
ERROR when selecting an "interpretation Flag" in **Case** creation

![image](https://user-images.githubusercontent.com/167875/140247847-60e0c9dc-1845-4ba4-ab4d-1f32350cc11e.png)

I guess that is a problem with a capitalization of the list items

**Comment by imedina** [comment]
@pamag this should be fixed now, can you review it?

**Comment by pamag** [comment]
## Reviewed 
The list is now in capital letters
![image](https://user-images.githubusercontent.com/167875/146685806-6e485f7d-0d3a-41a6-8a6e-139c93b0c6a3.png)
