### ISSUE TITLE
Some fields are not cleared after submitting a case

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#232]
## Description

After creating a case, the new form has some fields not properly filled and the "Management Information" comment persist from the previous case.

![image](https://user-images.githubusercontent.com/167875/140249054-70a83599-5eb2-4bd5-b396-8be238470d29.png)

**Comment by jmjuanes** [comment]
Clear comments and select fields of the create case form: 

![Peek 2022-01-03 17-01](https://user-images.githubusercontent.com/5751201/147952658-ffdaa155-0c8c-423d-aebd-e766f09b1b92.gif)

Notes: 

- Select fields (analysis type and priority) have been fixed as part of improvements made in other issues in `data-form` component.
- Clear comments field in commit 13193e1.
- The due date value is cleared in the HTML code when submitting the case, but in the rendered date input the previous date is still displayed:

![image](https://user-images.githubusercontent.com/5751201/147951684-6a4e35d3-d542-419a-8068-efaf491b9fe6.png)

**Comment by pamag** [comment]
## Reviewed
commit: ffe8b2e2848148b686e2aade147b79652ab0cc8c

** OK ** but date issue moved to new ticket https://github.com/opencb/jsorolla/issues/324
