### ISSUE TITLE
Improve Clinical-Analysis-Editor and fix some bugs

### ISSUE THREAD

**Issue by pamagz** [opencb/jsorolla#233]
## Description of the issue

The `clinical-analysis-editor` is still using the old components naming conventions. Also, it has some bugs when editing the case information.

## Proposed solution

- [x] Rename it as `clinical-analysis-update` to follow the new components naming convention.
- [x] Display errors returned by OpenCGA when the case is locked (we need first issue #248).
- [x] Disable fields when the `locked` option is turned ON.
- [x] **BUG**: fields are not marked as updated when the value is removed (for example when the content of a textarea is removed or we unselect all options in a select).
- [x] **BUG**: we can not update the case if we remove the content of the textarea

## Related tickets

- [x] https://github.com/opencb/jsorolla/issues/211

## Additional notes

- Evaluate moving the LOCK option outside the form (for example to the top-right side of the page).
- If the lock option is enabled, switch to view mode instead of disabling the form fields?

**Comment by jmjuanes** [comment]
**Note**: the lock option has been fixed in OpenCGA (Commit  https://github.com/opencb/opencga/commit/1bcecf5632c4c1780471d98295e68bc7ea42274f )

**Comment by jmjuanes** [comment]
Now all fields will be disabled when the `locked` option is enabled: 

![image](https://user-images.githubusercontent.com/5751201/140513338-cf25f41c-9376-4c0a-bbed-fa8fa7ebd5f3.png)

**Comment by jmjuanes** [comment]
Now updated fields are marked in orange (switch and textarea): 

![Peek 2021-11-05 14-31](https://user-images.githubusercontent.com/5751201/140519043-6caae00f-331a-4a44-964a-b05bc0519118.gif)

**Comment by jmjuanes** [comment]
The comments block should be also disabled when the `locked` option is enabled. There are two options to disable adding a new comment: 

1) Keep the **New comment** section but disable the text fields of this section:

![image](https://user-images.githubusercontent.com/5751201/140536022-588f3c79-55ed-462f-a1d7-d97309d397c2.png)

2) Hide the **New comment** section. The problem with this option is what to do when there are no comments to prevent displaying an empty block. 

![image](https://user-images.githubusercontent.com/5751201/140535907-a56d8dea-5be1-4ed0-9bfa-df8bfad48137.png)

**Comment by jmjuanes** [comment]
The task ` Display errors returned by OpenCGA when the case is locked.` is blocked until we decide what to do with the notification management.

**Comment by jmjuanes** [comment]
Issue #248 has been completed and merged into `release-2.2.x`. Displaying errors returned by OpenCGA (if any) updating the clinical case using the new notifications manager (commit df53161).

**Comment by pamag** [comment]
## REviewed

FIXED
