### ISSUE TITLE
Variant exporter description

### ISSUE THREAD

**Issue by pamagz** [opencb/jsorolla#234]
## Description of the issue

At this moment some users want to feature the **Variants Exporter** tool, but at this moment it does not have a description so there is an empty space in the featured block:

![image](https://user-images.githubusercontent.com/93584709/140505383-088929c7-1cd9-4a07-a9c7-40cf9ace87f6.png)

## Proposed solution

Use the following text as the description of the **Variant Exporter** tool:

> Filter and export variants, with their annotation and sample genotypes, from the Variant Storage to a file in multiple supported formats (vcf, json, tped, ensembl vep tab...) for being shared or processed by an external tool.

**Comment by jmjuanes** [comment]
Added description of the **Variant Exporter** tool in commit 31b4e40:

![image](https://user-images.githubusercontent.com/5751201/140738873-0db1006a-c786-4ff5-a39c-25d4244e0c21.png)
