### ISSUE TITLE
Remove error message for empty grids

### ISSUE THREAD

**Issue by pamagz** [opencb/jsorolla#236]
# Description

When a grid does not return any value it shows an ERROR message at the bottom of the grid,  but it is not an error indeed.

i.e.: interpretation_review/primary_findings where no variants has been selected yet

![image](https://user-images.githubusercontent.com/93584709/140516847-27d93546-a177-4f7b-87ee-9d0837dec711.png)

# Proposal

This is not an error. And already "warned" inside the grid

![image](https://user-images.githubusercontent.com/93584709/140516659-b7a9b2bf-6598-4a33-8489-cf60bae29752.png)

**ACTION** Remove the error message

# Related bugs
- [x] https://github.com/opencb/jsorolla/issues/230

**Comment by pamag** [comment]
## Reviewed

Closed -> fixed in #356
