### ISSUE TITLE
Some improvements to the new navigation cards

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#237]
## Description

Initial navigation cards are two big and flow in several columns, and need the link associated to the whole card not only to the enter button.

![image](https://user-images.githubusercontent.com/167875/140790789-f5214e6c-5a98-4a95-a6df-7300e05e8c2e.png)

## Tasks

- [X] ~~Allow click in any place of the card~~. To allow the user to copy the tool description, we will allow clicking in the card icon and title and increase the **Enter** button size.
- [X] ~~Reduce the card size~~. We recommend not displaying more than 4 featured tools on the welcome page.

**Comment by jmjuanes** [comment]
Allow clicking in the card icon and the title (commit 7cf60ee): 

![image](https://user-images.githubusercontent.com/5751201/141975644-fee15e3f-b3e8-4159-9df9-2728d0bf9e20.png)

**Comment by jmjuanes** [comment]
Changed size of cards buttons in commit 518d5e5: 

![image](https://user-images.githubusercontent.com/5751201/141975912-b079db7a-c2b0-4b34-9b11-7910f4bf2e99.png)
