### ISSUE TITLE
Dependency upgrade needed GRUNT-CURL

### ISSUE THREAD

**Issue by jcortell** [opencb/jsorolla#24]
~1.1.1 REQUESTED
2.2.0 LATEST STABLE
14 RELEASES BEHIND

Risky upgrade:  Take caution in upgrading this dependency as it may have breaking changes in its latest release.

How behind is this version?
1 BREAKING RELEASE
6 FEATURE RELEASES
7 PATCH RELEASES

NESTED SECURITY ADVISORIES
qs Denial-of-Service Extended Event Loop Blocking
Discovered in a nested dependency:grunt-curl@1.1.1request@2.21.0qs@0.6.6
qs Denial-of-Service Memory Exhaustion
Discovered in a nested dependency:grunt-curl@1.1.1request@2.21.0qs@0.6.6
Regular Expression Denial of Service
Discovered in a nested dependency:grunt-curl@1.1.1request@2.21.0hawk@0.13.1

**Comment by agaor** [comment]
Thank you very much for your contribution.
Now grunt is removed from the Jsorolla project. Only npm is available.
