### ISSUE TITLE
case creation: if no case_id, the OK button should be disabled

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#241]
## Description

1- If case_Id is empty `OK` button should be disabled. The message of "invalid identified format for id" is confusing
2- the same for "proband_id" (but here, the message is more appropriate)

Case_id missing
![image](https://user-images.githubusercontent.com/167875/140835777-80db8f00-e86f-4e2e-a3a4-0afb4999e786.png)

Proband missing:
![image](https://user-images.githubusercontent.com/167875/140839893-e2600432-2f3e-48a5-9275-c203080bc039.png)

**Comment by imedina** [comment]
@jmjuanes @Rodielm the best way of solving this is by implementing a form validation in `data-form` that disables `OK` button if something is not correct

**Comment by Rodielm** [comment]
Fixed
`test user: demouser`

![ClinicalCreate](https://user-images.githubusercontent.com/10471758/142420613-3bb15ff7-20df-443b-b802-0db94c3530c9.gif)

**Comment by imedina** [comment]
@pamag this should be fixed now :-)

**Comment by pamag** [comment]
@imedina is the proband really mandatory to create a case?

**Comment by Rodielm** [comment]
Fixed
Test User: `demouser` 

It displays which fields are required and checks if the value is valid.

![TestCase4](https://user-images.githubusercontent.com/10471758/142665257-f586ac8a-0225-434a-915d-1ff43143a64b.gif)

**Comment by pamag** [comment]
suggestion: add a footnote with 'Fields with a red * are mandatory'

Also, I think that `Select disorder` is not mandatory @Rodielm please review that

**Comment by Rodielm** [comment]
disorder is no longer a mandatory field - https://github.com/opencb/jsorolla/commit/3023d7b4c23a1357151d7466f2aeaa95a14a1178
![image](https://user-images.githubusercontent.com/10471758/147365814-b7d17157-73f9-4891-bcb9-9ecd7a28cb45.png)

**Comment by pamag** [comment]
## Review
commit: 3023d7b4c23a1357151d7466f2aeaa95a14a1178

Done
* Update button is always active but mandatory items had a red start in the name.
* If any mandatory parameter is missing a message below the text area is displayed if the updated button is clicked.
