### ISSUE TITLE
case creation: the proband_id badge is not cleared with "CANCEL""

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#242]
## Description
[ Git: develop - 82077799e98e4a3a75a13d89ef81d4d05508c9d7]

In the case creation window, the "CANCEL" button does not clear the Proband_id badge (but it does clear the data)

![image](https://user-images.githubusercontent.com/167875/140837901-158fe7c6-a05b-4225-af5d-e32d40543c48.png)

**Comment by Rodielm** [comment]
Fixed in this commit: ad142f9 and related to issue #241

**Comment by pamag** [comment]
## Reviewed
OK
