### ISSUE TITLE
case interpreter: "variant browser"  "gene panel" filter needs new lines for separate panels in the pop up

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#245]
## Description

In the "Variant Browser" in the "Case Interpreter" when several "Gene Panels"  are selected, each panel need to be in a new line, not as comma separated in the same line that the indented description of the previous panel.

![image](https://user-images.githubusercontent.com/167875/140843808-bcd1c9da-735f-45f5-ac24-052f45e752d0.png)

**Comment by Rodielm** [comment]
Fixed
The separator  `","`  has been changed to a line break.

![ClinicalDisease](https://user-images.githubusercontent.com/10471758/142889981-4f05e668-f49a-4cb2-b7e0-f83e63880b37.gif)

**Comment by pamag** [comment]
## Review

@Rodielm in commit 42dfd21991711e3bc06fd5ed5f295fe4b4a286ca

it is not working
![image](https://user-images.githubusercontent.com/167875/147304083-d47fd44e-5e48-4ebb-b3f4-782c1173ab0e.png)

**Comment by pamag** [comment]
## Reviewed

commit: f104bd4712825f4c4fdc278c088a4b7b7bff1bf0

FIXED

![image](https://user-images.githubusercontent.com/167875/150710158-11b2738f-5b84-42f0-ad71-cabcbae82664.png)
