### ISSUE TITLE
Redesign Notifications manager

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#248]
## Description 

At this moment we are using two notification systems:

- **bootstrap-notify**, for displaying notifications at the top side of the web application: 
![image](https://user-images.githubusercontent.com/5751201/141093315-6fb041d8-c798-4c0b-8123-5ae6bfd9133a.png)

- **sweetalert2**, for displaying blocking (and sometimes annoying) notifications or confirmation dialogs:
![image](https://user-images.githubusercontent.com/5751201/141102011-1319e2e9-184e-45d4-a20d-a5871a9ba62b.png)

There are some problems when displaying errors: the notification sometimes is too small and also you do not have enough time to read and copy the error message: 

![image](https://user-images.githubusercontent.com/5751201/141103151-199177e0-e6c5-4e0a-9097-d198045fab9a.png)

Also, there are three JS files in different places for managing the notification: 
- **src/core/NotificationQueue.js**: https://github.com/opencb/jsorolla/blob/63d4721dcf1b21c44b441ac48f6d3e2b9669f5a1/src/core/NotificationQueue.js 
- **src/webcomponents/Notification.js**: https://github.com/opencb/jsorolla/blob/63d4721dcf1b21c44b441ac48f6d3e2b9669f5a1/src/webcomponents/Notification.js
- **src/webcomponents/NotificationUtils.js**: https://github.com/opencb/jsorolla/blob/63d4721dcf1b21c44b441ac48f6d3e2b9669f5a1/src/webcomponents/NotificationUtils.js

## Proposed solution

Implement a pure JavaScript notification manager that will use:
- bootstrap alert components for displaying notifications (1st phase).
- sweetalert2 for backward compatibility for confirmations (1st phase).
- bootstrap modal component for displaying confirmation dialogs (2nd phase).

The new notification manager will be placed in the `core` folder, so we can use it in all **jsorolla**.

### Design prototypes 

Success notification that will be hidden automatically after a specific number of seconds: 

![image](https://user-images.githubusercontent.com/5751201/141102894-c1c7ab1d-7953-4603-b492-09449e596e86.png)

Allowing displaying multiple notifications: 

![image](https://user-images.githubusercontent.com/5751201/141103330-4617a046-cc5a-4d6f-9063-37cc4d01ec37.png)

Error messages will remain active until the user press the **Close** button, so he will have time to copy the content. In the future, we can have an additional button to report the problem automatically. 
 
![image](https://user-images.githubusercontent.com/5751201/141103517-bc0eda67-f419-4a23-894e-b2236df73ec3.png)

### API specification

We will have a common method for displaying a notification alert: 

```javascript
Notification.show({
    type: "danger",
    title: "Notification title",
    message: "Lorem ipsum dolor sit amet, consectetur...",
    removeAfter: 0,
    display: {
        showIcon: true,
        showCloseButton: true,
        alertClassName: "",
        buttonClassName: "",
    },
    buttons: [
        {text: "Close", onClick: () => { }},
    ],
});
```
- `type`: type of the notification: `success`, `info`, `warning` or `danger`.
- `title`: a string with the notification title.
- `message`: a string with the body of the notification.
- `icon`: a string with the class of the icon that should be displayed in the notification. If not specified, the notification manager will display an icon depending on the notification type.
- `removeAfter`: automatically hide the notification after the specified milliseconds. By default, it will be `0` (do not hide the notification). 
- `display`: an object with the display configuration. Allowed fields: 
  - `showIcon`: boolean to display the icon at the left side of the notification.
  - `showCloseButton`: boolean to display the close button at the right side of the notification.
  - `alertClassName`: a custom class for the notification alert.
  - `buttonClassName`: a custom class for the buttons displayed in the notification.
- `buttons`: a list of buttons to display at the end of the notification. Each button can be configured using the following parameters:
  - `text`: text to display in the button.
  - `onClick`: a function that will be executed when the user clicks on the button.
  - `removeOnClick`: a boolean to automatically remove the notification after this button is clicked. 

We will have shortcuts for displaying common notifications, that will call `Notification.show` with a specific configuration: 

```javascript
Notification.success("title", "message");
Notification.info("title", "message");
Notification.warning("title", "message");
Notification.error("title", "message");
```

### Displaying response notifications

We will also create a helper function called `showResponse` that will accept an OpenCGA `response` object, and will generate a notification for error and warning response events.

### Displaying notifications

We will create an instance of the Notification manager in the main component of each app, and register events listeners for displaying notifications:

```javascript
this.addEventListener("notify", e => this.notificationManager.show(e.detail));
```

Common notifications can be also displayed using an event, but in that case the `event.detail` object must contain a `title` and a `message` field:

```javascript
LitUtils.dispatchEventCustom(this, "notifyError", null, null, {
    title: "Error title",
    message: "Error message",
});
```

Response notifications can be also displayed passing the `response` object as the `event.detail.value` field:

```javascript
LitUtils.dispatchEventCustom(this, "notifyResponse", response);
```

**Comment by jmjuanes** [comment]
First implementation of the new Notifications Manager (commits 04849be, 152b54c and 4f62d45) and tested with the notifications of the login and the session expiration alerts: 

![image](https://user-images.githubusercontent.com/5751201/141486184-537ef30f-e6bf-4092-868e-ede87eb5277f.png)

![image](https://user-images.githubusercontent.com/5751201/141486327-599c0d32-6213-4c86-98a3-8ea146b811c0.png)

**Comment by jmjuanes** [comment]
First implementation of the new notifications manager:

![image](https://user-images.githubusercontent.com/5751201/143430921-a65f5374-2962-4418-86b5-d74f1ac5c7fb.png)

Finally we decided to display notifications using custom events instead of calling a static method of the Notifications class. For that reason, we are creating an instance of the Notifications class in the **IVA-APP** component, and registering the following events: 

https://github.com/opencb/jsorolla/blob/b94d790b2121cce5242519e29194a82e64608db3/src/sites/iva/iva-app.js#L262-L272

**Comment by jmjuanes** [comment]
Added title support in notifications (commit 6c55a97): 

![image](https://user-images.githubusercontent.com/5751201/143480273-93d3159a-0151-4d86-a064-2e82126bd5d8.png)

**Comment by jmjuanes** [comment]
Updated notification in some components: 

![image](https://user-images.githubusercontent.com/5751201/145582492-6ec98243-900d-41a0-aff4-814efcb201ba.png)

**Comment by pamag** [comment]
## Reviewed

commit: f104bd4712825f4c4fdc278c088a4b7b7bff1bf0

FIXED
