### ISSUE TITLE
Job Browser: Select a row

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#249]
## Description

At this point the Job Browser has an unexpected behaviour that may confuse the user.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select one of the rows (not the first one).
2. Click on 'refresh or force refresh'.
3. See wrong behaviour: the row selected is gone, the table selected the first by default.

## Expected behaviour
Although the job browser does update or refresh if the user selected a row, it must still be selected.

**Solution**

- An event (onClick) to get the job ID of the row clicked
- After a refresh behavior, Find which is the selected row
- Highlight the row was selected

**Comment by Rodielm** [comment]
Fixed
![JobBrowser4](https://user-images.githubusercontent.com/10471758/141487907-03bc785e-1c17-4a43-af0c-3a511f05cc43.gif)

**Comment by pamag** [comment]
## Reviewed

commit: f104bd4712825f4c4fdc278c088a4b7b7bff1bf0

FIXED
