### ISSUE TITLE
Dependency upgrade needed GRUNT-CONTRIB-WATCH

### ISSUE THREAD

**Issue by jcortell** [opencb/jsorolla#25]
VERSION DETAILS

~0.5.3 REQUESTED
1.0.0 LATEST STABLE
3 RELEASES BEHIND

Risky upgrade: Take caution in upgrading this dependency as it may have breaking changes in its latest release.

How behind is this version?
1 BREAKING RELEASE
1 FEATURE RELEASE
1 PATCH RELEASE

NESTED SECURITY ADVISORIES

qs Denial-of-Service Extended Event Loop Blocking
Discovered in a nested dependency:grunt-contrib-watch@0.5.3tiny-lr@0.0.4qs@0.5.6
qs Denial-of-Service Memory Exhaustion
Discovered in a nested dependency:grunt-contrib-watch@0.5.3tiny-lr@0.0.4qs@0.5.6

**Comment by agaor** [comment]
Thank you very much for your contribution.
Now grunt is removed from the Jsorolla project. Only npm is available.
