### ISSUE TITLE
variant browser aggregation by type dropdown is missing `mnv`

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#251]
## Description

variant browser aggregation by type does not have `mnv` in the type dropdown but there are mnv variants in the plot

![image](https://user-images.githubusercontent.com/167875/141341180-36aa0493-57a5-454d-bb65-1bade0e8edb2.png)

**Comment by imedina** [comment]
@pamag actually both _type_ filters in the browser and aggregation need to be updated

**Comment by pamag** [comment]
FIX: 
Define a variable VARIANT_TYPES in `src/sites/iva/conf/opencga-variant-constants.js`

```
VARIANT_TYPES = ["SNV", "INDEL", "MNV", "COPY_NUMBER", "INSERTION", "DELETION", "DUPLICATION", "SV"];
```
and use in `src/webcomponents/variant/variant-browser.js`

see https://github.com/opencb/jsorolla/commit/687b659a8542c35c3ab430fd2ef968deaf6fb419

**Comment by pamag** [comment]
There is still some issues. 

- [ ] VARIANTS_TYPES is missing `breakend` item  => probably we need to make the variant types dynamic as depending on the source they could use nonstandard ones.
![image](https://user-images.githubusercontent.com/167875/142519321-57d761e8-0db9-4707-83ac-773118f7dfb1.png)

- [ ] The plot only show variant types with at least one element this is the reason MNV is not plotted in this case. [note] If the list of variant_types is small one option is to plot all categories. 
- [ ] Think about if the sorting could  be optional (would need a control for that)

**Comment by pamag** [comment]
## Reviewed

FIXED
