### ISSUE TITLE
Clinical interpreter: can not remove a panel from the Disease Panels selector

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#253]
## Describe the bug

If a panel is removed from the **Disease Panels** selector, after updating the case the removed panel is marked again as selected.

## To Reproduce

1. Go to **Case portal**.
2. Open a case.
3. Remove a panel from the **Disease Panels** selector.
4. Save the case info.
5. The removed panel is displayed again as selected.

## Screenshots

Remove a panel from the **Disease panels** select: 

![image](https://user-images.githubusercontent.com/5751201/141776106-39c6b644-e0cd-4e40-8f3c-9acf35c50d11.png)

After updating the case, the removed panel is selected again: 

![image](https://user-images.githubusercontent.com/5751201/141776238-ef9b76c4-d7a4-4549-bb2c-ec744424b33c.png)

**Comment by jmjuanes** [comment]
Fixed in commit 166b575: manually set the `panelsAction` parameter to `SET`, so OpenCGA will change the list of panels to the new panels that we are providing:

https://github.com/opencb/jsorolla/blob/166b575ad4304312cfa80d74acd9524e7dc64aa5/src/webcomponents/clinical/clinical-analysis-update.js#L204 

Minor style update in commit b4e063b: 

https://github.com/opencb/jsorolla/blob/b4e063b09a5630fb3baee45b3384688d25bf7aa1/src/webcomponents/clinical/clinical-analysis-update.js#L202-L206

**Comment by pamag** [comment]
## Reviewed
commit f6bea023104151cf7a24ffa94c620aea8fdd23de
OK
