### ISSUE TITLE
iva: Complete default apps descriptions

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#256]
## Description

Review and complete the descriptions of the apps

Featured
![image](https://user-images.githubusercontent.com/167875/141825617-cc7e5444-f80d-4139-a549-772681f7d438.png)

![image](https://user-images.githubusercontent.com/167875/141824701-4ca01d14-0b76-44ad-a487-0e0edbbf9b7e.png)

![image](https://user-images.githubusercontent.com/167875/141825478-31c14892-d63f-4cdf-b815-0b3dbedfe9f5.png)

![image](https://user-images.githubusercontent.com/167875/141825521-b997f856-960c-4fad-9d36-caf916661a6d.png)

![image](https://user-images.githubusercontent.com/167875/141826227-b481b70a-1d4d-4e6c-8660-7ad5c9724bca.png)

---

**Comment by imedina** [comment]
@pamag can you prepare the first draft for all descriptions?

**Comment by pamag** [comment]
> @pamag can you prepare the first draft for all descriptions?

yes

**Comment by pamag** [comment]
## Reviewed

FIXED

![image](https://user-images.githubusercontent.com/167875/152253947-1f61622a-89dd-4a44-a656-fac205f74efd.png)
![image](https://user-images.githubusercontent.com/167875/152253987-0071fb79-be34-497c-bb73-d7bb0eda2791.png)

still the admin is not filled but we leave for later.
