### ISSUE TITLE
iva: issues with apps links  when log out.

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#257]
### 1-- When logged out, all apps show a message advising to log in in order to see the data.

![image](https://user-images.githubusercontent.com/167875/141877669-764b6258-6636-414a-bcd5-79633e0efdcb.png)

But in **"create case"** is blank, no message at all.

![image](https://user-images.githubusercontent.com/167875/141827338-a5b32043-d1b3-4d41-a489-c03990149869.png)

---
### 2-- click down in the apps card do nothing when log out
 
![featured_apps_no_login](https://user-images.githubusercontent.com/167875/141877993-3da4f780-bf1b-4b4d-9692-f301238f7321.gif)

But when clicked down in the menu it goes to the page with a note advising to log in.
![featured_apps_no_login-card_vs_menu](https://user-images.githubusercontent.com/167875/141878285-f55ef4cb-24e4-4b29-b547-4d3074caffe1.gif)

**Comment by imedina** [comment]
@Rodielm can you check this issue? BTW, I'm not observing the exact behaviour reported. The only issue seems to be the blank page in the new Create Case

**Comment by Rodielm** [comment]
Fixed, New creation case will display a message if the user is not logged in.

![CreateCaseNotLogin](https://user-images.githubusercontent.com/10471758/142183705-6bf133f4-b9ab-44e6-8e05-8110271edccc.gif)

**Comment by pamag** [comment]
## Reviewed

FIXED
