### ISSUE TITLE
Gene filter uses a deprecated component

### ISSUE THREAD

**Issue by imedina** [opencb/jsorolla#258]
Gene filter is implemented in `feature-filter` component, and this is using a deprecated component called `select-token-filter`, this needs to be updated:

https://github.com/opencb/jsorolla/blob/develop/src/webcomponents/commons/filters/feature-filter.js#L121

**Comment by Rodielm** [comment]
Feature-filter component use the latest `select-token-filter`, https://github.com/opencb/jsorolla/blob/develop/src/webcomponents/commons/filters/feature-filter.js#L19

The other token filter has been moved to deprecated: https://github.com/opencb/jsorolla/blob/develop/src/webcomponents/commons/filters/deprecated/select-token-filter.js

**Comment by pamag** [comment]
## Reviewed
   - OpenCGA commit: bcbe75e68198a1171ad977e747189ddcdbc74c39
   - IVA commit: 6df12c6cdc47629a3b362fe8150c53debfb501e2

Gene filter works OK
