### ISSUE TITLE
Case interpreter: migrate to detail tabs component

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#259]
## Description

In the **Case interpreter** portal, some steps are using the old tabs implementation: 

![image](https://user-images.githubusercontent.com/5751201/142184605-4f045e21-8834-45ca-8329-ff03ac6dc8aa.png)

This implementation has several know bugs, as described in some issues like #222.

## Proposed solution

Use the `detail-tabs` component to manage tabs instead of using the current implementation in each step. This component is already in use in the **Interpretation Review**: 

![image](https://user-images.githubusercontent.com/5751201/142185236-c7127b9a-a649-4a23-ae5f-c6ae3e1a715d.png)

**Comment by jmjuanes** [comment]
Migrated the **Case Manager** step to `detail-tabs` in commit 123c036: 

![image](https://user-images.githubusercontent.com/5751201/142208369-1bfa9559-6129-45e1-9e4c-06ada298f7cd.png)

**Comment by jmjuanes** [comment]
Migrated the **Sample Variant Browser** step to `detail-tabs` in commit 7d2b56e:

![image](https://user-images.githubusercontent.com/5751201/142244516-ea341b4f-6556-41e2-89f7-735fcb2eb1e2.png)

![image](https://user-images.githubusercontent.com/5751201/142244694-69d6e6f4-f0d6-4f7f-976e-f294ee7fbcea.png)

**Comment by jmjuanes** [comment]
Migrated the **Quality Control** step to `detail-tabs` in commit 2724ef0: 

![image](https://user-images.githubusercontent.com/5751201/142256105-f450bb7e-1489-4e84-b552-1696be551f4f.png)

**Comment by pamag** [comment]
## Reviewed ##
