### ISSUE TITLE
Improve description "Download table" in "Variant browser" export button

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#264]
**Is your feature request related to a problem? Please describe.**

In the 'Variant Browser' export button, the description of tab "Download Table" can be improved.
 
Current text is :
```
 Note: This option will automatically download the table, note that only first 1,000 records are downloaded.
```
![image](https://user-images.githubusercontent.com/167875/142709741-7776d5a9-8079-48a5-ac73-410e79fc4aca.png)

I would like to give extra information just in case people wants more than 10000 samples.

**Describe the solution you'd like**
 I would suggest the following text:
```
 Note: This option will automatically download the table, note that only first 1,000 records are downloaded.
(If you need all records, please use 'Export Query')
```

**Comment by antonioaltamura** [comment]
As a relevant information, please note that the tabs are also configurable through external settings
https://github.com/opencb/jsorolla/blob/issue-421/src%2Fwebcomponents%2Fvariant%2Fvariant-browser-grid.js#L137
