### ISSUE TITLE
Bug displaying filters of the Case Interpreter Portal

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#265]
## Description

After changes implemented in #263, filters in the **Case Interpreter Portal** are displayed as block elements instead of inline elements: 

![image](https://user-images.githubusercontent.com/5751201/142888255-ea63d4b3-b055-4ca3-95f2-06fb6bec1053.png)

## Expected behaviour 

All filters should be displayed inline:

![image](https://user-images.githubusercontent.com/5751201/142887768-cb4479de-46b8-4a5c-842f-b13200fe67d0.png)

**Comment by jmjuanes** [comment]
Found bug in `select-token-filter` component after this commit: https://github.com/opencb/jsorolla/commit/eb4b90f9243682dee534ad78ccc127ad7d259b2c

Fixed in commit 1d58ec6. Keep original `select-token-filter` component if file upload is disabled:

![image](https://user-images.githubusercontent.com/5751201/142889013-d1c81c39-0307-4458-b76a-29b02222d6e2.png)

**Comment by pamag** [comment]
## Reviewed
OK
