### ISSUE TITLE
Upgrade to new OpenCGA QualityControl data models

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#266]
## Description 

As a result of the changes implemented in opencb/opencga#1844, some data models have been updated and now are using the field `files` instead of `images`, `fileIds` or `genomePlots`.

**Comment by Rodielm** [comment]
Fixed:  `images` field rename as `files` in `FileQcAscatMetrics`

![image](https://user-images.githubusercontent.com/10471758/143050482-a3efc50a-ea49-45c1-96e4-dc29d31b56f8.png)


![image](https://user-images.githubusercontent.com/10471758/143050699-809f3d9d-9978-4567-8b88-12e765219d08.png)

**Comment by pamag** [comment]
## Reviewed
OK
