### ISSUE TITLE
Improve jobs browser refresh interface

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#267]
## Description

Currently, the refresh interface of the jobs browser is very confusing:

- Is not clear for the users that the button with the bolt icon forces a refresh of the jobs list. Usually, **the user expects a refresh icon instead of a bolt icon**.
- The reload icon that is always spinning gives the impression that there is a running request in the background that never ends...

![image](https://user-images.githubusercontent.com/5751201/143219541-e267e0f6-2005-42a0-87c8-4fc8e5d8978d.png)

Also, there is a refresh delay of 15 seconds, which means that in a minute there will be 4 refresh requests. Taking into account that jobs may take more than an hour to complete, we should increase the refresh delay to reduce the number of refresh requests to the server. 

## Suggested improvements

- [X] Replace the bolt icon with a refresh icon and display a **Refresh** text beside the icon to make it much clear for the user.
- [x] Display the reload icon only when there is a refresh request in process.
- [x] Change the refresh delay to 60 seconds.

**Comment by jmjuanes** [comment]
Changed bolt button to refresh button in commit 37db758

![image](https://user-images.githubusercontent.com/5751201/143225964-8bfdf623-71ab-4ca7-952f-f4fcc46b63b6.png)

**Comment by jmjuanes** [comment]
Display the refresh icon beside the pagination info only if there is a refresh request pending (commit 5a8ccb2): 

![Peek 2021-11-24 16-21](https://user-images.githubusercontent.com/5751201/143266126-f01ca8a7-dd86-404d-ac92-08aee3a7483e.gif)

**Comment by jmjuanes** [comment]
Changed default autorefresh delay to 60s in the Job grid default configuration (commit aa056bd): 

https://github.com/opencb/jsorolla/blob/aa056bd731470ccd664a476e34079f870686ede2/src/webcomponents/job/job-grid.js#L529

**We will need also to change this value in the Job Browser settings**. Changed in the default settings of the IVA application (commit 8bac5b5): 

https://github.com/opencb/jsorolla/blob/8bac5b5392513095766bc62a83027e6bc72ebd25/src/sites/iva/conf/opencga-job-browser.settings.js#L22

**Comment by imedina** [comment]
@pamag ready to review

**Comment by pamag** [comment]
## Reviewed

FIXED
