### ISSUE TITLE
Improve *-detail component

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#269]
## Description

At this moment almost all `*detail` components do not have a check, validation or verification before displaying data to the user. 

## Solution 

To avoid unexpected behaviour, ~all `*-detail` components will contain a check, verification or validation conditions depending on the type of data being passed to the `*-detail` component.~  the main component of the detailed tabs will contain a general check, if the data or other properties are not correct, nothing will be displayed, only a message.

**Comment by pamag** [comment]
## Reviewed

FIXED
