### ISSUE TITLE
New Site: Rest Api App

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#273]
## Description
Unfortunately, Swagger has its own disadvantage, as more endpoints or services are added the page is slower.

## Proposed Solution
It's necessary to implement an interactive opencga documentation. 
* easy to use.
* faster app.
* More features we have in mind.

**Comment by pamag** [comment]
## Reviewed

commit: f104bd4712825f4c4fdc278c088a4b7b7bff1bf0

CREATED first MVP
![image](https://user-images.githubusercontent.com/167875/150712269-93c09b22-1c93-442a-8e02-a5f53d687d52.png)

There are still things to improve but this is a working prototype.
