### ISSUE TITLE
Allow lock/unlock the case from the actions menu

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#275]
## Description 

On issue #226 we introduced the **Actions** menu in the Case Interpreter toolbar to easily allow the user to perform some actions to the case (change the primary interpretation, download and refresh the case, and close the interperter).

![image](https://user-images.githubusercontent.com/5751201/144083212-9a4b24e2-3e40-4b09-877a-9a7f02d7c846.png)

We need to allow the user to easily lock and unlock the case. At this moment, the only way to do this is to go back to the **Case Info** step and lock the case in the **Case Manager** tab. We decided to add the **Lock** and **Unlock** actions to the Actions menu and display a lock icon next to the case ID if the case is locked. 

## Tasks

- [x] Add action to lock and unlock the case in the **Actions** menu.
- [x] Display a lock icon next to the case ID when the case is locked.

**Comment by jmjuanes** [comment]
Added action to lock or unlock a case from the Actions menu in commit 511dff3: 

![Peek 2021-12-22 17-07](https://user-images.githubusercontent.com/5751201/147121795-6d3d8fb6-42e5-492b-afef-6939768b5017.gif)

**Comment by jmjuanes** [comment]
Displaying a lock icon with the Case ID when the case is locked (commit 0b53e6a): 

![image](https://user-images.githubusercontent.com/5751201/147123193-12d345d5-c445-482a-953f-d4e8a689c834.png)

**Comment by pamag** [comment]
## Reviewed
commit 905480934bab2042035f1112de49bec57bb1ab2f
OK
