### ISSUE TITLE
Unable to create cancer or family cases

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#277]
## Describe the bug

After filling the form for creating a new CANCER or FAMILY case, clicking in the **Create** button does nothing and no error message is displayed neither in the UI nor in the console.

## Steps to reproduce

1. Select the **Illumina Platinum** study.
2. Go to **Case Interpreter portal** and click on the **New** button.
3. Type a valid case ID.
4. Select **CANCER** in the analysis type.
5. Select the proband **NA12877** in the cancer analysis configuration section.
6. Click on the **Create** button. 
7. Nothing happens. No request has been made to the server and no error is displayed on the screen or in the console.

## Expected behavior

We expect at least an error message if something is missing in the form.

## Screenshots

![Peek 2021-12-01 12-42](https://user-images.githubusercontent.com/5751201/144228508-8c4c410f-2d06-4b63-a95d-bdf55de4bf6b.gif)

**Comment by jmjuanes** [comment]
Found bug in `data-form`: the field `proband.id` is marked as required when submitting the form: 

![image](https://user-images.githubusercontent.com/5751201/144229110-398e6fd5-dde4-4edd-9241-19d0bc75cb2c.png)

But the `proband.id` has been marked as required when the case is **SINGLE** (line 407), not when the case is **CANCER**: 

https://github.com/opencb/jsorolla/blob/72220632a64c56b13dafc9fcd0785bd5ce0483d5/src/webcomponents/clinical/clinical-analysis-create.js#L398-L408

https://github.com/opencb/jsorolla/blob/72220632a64c56b13dafc9fcd0785bd5ce0483d5/src/webcomponents/clinical/clinical-analysis-create.js#L583-L594

That means that the `proband.id` field is marked as required when the form is rendered the first time (because initially the type is **SINGLE**). But when we change the analysis type to **CANCER**, **this field is not removed from the required list**.

**Comment by jmjuanes** [comment]
Bug fixed on commit 14062ae: reset `emptyRequiredFields` and `invalidFields` sets each time we update the form: 

https://github.com/opencb/jsorolla/blob/14062ae68467bf0440068d406aa4b7e9961b2497/src/webcomponents/commons/forms/data-form.js#L85-L97

Now fields from hidden sections do not count as empty required fields: 

![image](https://user-images.githubusercontent.com/5751201/144237153-24fd5caa-1d8f-4257-b747-96f2c286ed1a.png)

Also, the request is made to OpenCGA after submitting the form and if something is wrong an error message is displayed: 

![image](https://user-images.githubusercontent.com/5751201/144237617-6363d6bf-f304-49ef-ac75-75456309a30e.png)

**Comment by pamag** [comment]
Now if the proband does not have a somatic sample it can not be created.

**Comment by pamag** [comment]
reviewed and closed
