### ISSUE TITLE
Some bugs updating an interpretation

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#279]
## Describe the bug

We have found two bugs when updating an interpretation:

1. When clicking on the **Edit** button of any interpretation, the modal always displays the information about the first interpretation.

2. Additionally, if we try to save the interpretation, an error message is displayed in the application (see screenshots).

## To Reproduce

Steps to reproduce the first bug: 

1. Select **Illumina Platinum** study.
2. Open the **Case Portal** and select the first case, **NA12877**.
3. In the *Case Info** section, open the **InterpretationManager** tab and click on the **Edit** button of any of the secondary interpretations.
4. You will see that the info of the primary interpretation is always displayed in the modal, instead of the information of the desired interpretation.

Steps to reproduce the second bug:
1. Follow steps 1-3 of the first bug.
2. Make some changes in the interpretation.
3. Click on the **Update** button.

## Expected behavior

For the first bug, if we click on the **Edit** button of the second interpretation we should be able to see and edit the configuration of the second interpretation.

For the second bug, we should be able to update the interpretation with the changes made in the modal.

## Screenshots

1. Wrong interpretation displayed in the modal: 

![image](https://user-images.githubusercontent.com/5751201/144277065-2afc44ac-0fd3-49bc-8364-c10c9409f366.png)

2. Error updating an interpretation: 

![image](https://user-images.githubusercontent.com/5751201/144280413-276724fa-66d2-44d3-b226-0d98678fa09a.png)

**Comment by jmjuanes** [comment]
Found bug: the `clinical-interpreation-update` was always getting the primary interpretation. Fixed in commit 3e6cc2a: 

![image](https://user-images.githubusercontent.com/5751201/144278773-adbc252c-2f3c-4a36-9788-bcbd8c4b4e39.png)

![image](https://user-images.githubusercontent.com/5751201/144277993-1923980c-07e3-4946-ae4d-460eea7f59c6.png)

**Comment by jmjuanes** [comment]
**Fixed the second bug** in commit 1788178: 

![image](https://user-images.githubusercontent.com/5751201/144286009-c54d42e7-b7bd-4f02-9343-76a521fb4fc8.png)

**Comment by pamag** [comment]
reviewd and closed
