### ISSUE TITLE
Unable to check a filter checkbox by clicking in the text

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#280]
## Describe the bug

Some of the checkboxes in the **Select SO terms** filter can not be checked by clicking in the label text.

## To Reproduce

1. Open the **Variant Browser** in the **Illumina Platinum** study.
2. Expand the **Consequence type** filters group.
3. Try to check some of the checkboxes by clicking on the text.

## Expected behavior

Checkboxes should be checked by clicking in the text.

## Screenshots

![Peek 2021-12-02 16-52](https://user-images.githubusercontent.com/5751201/144456180-8a97e26c-cff4-4d53-b5b7-a72fec295fe2.gif)

## Additional context

This usually happens when there is a blank space in the label text.

**Comment by jmjuanes** [comment]
Fixed bug in commit 678a3fc: there was a bug generating the ID for the label and checkbox when there is a blank space in the name. 

![Peek 2021-12-02 17-36](https://user-images.githubusercontent.com/5751201/144464496-6fb9c00f-e484-43f2-b42e-e3c2f3a12ab4.gif)

**Comment by pamag** [comment]
reviewed and closed ticket
