### ISSUE TITLE
case interpretation `new` button needs to be a bit upwards 

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#282]
## Description
Case Interpretation `new` button needs to be a bit upwards 

![image](https://user-images.githubusercontent.com/167875/144548348-661f7d35-c9e6-4a5d-8caf-0d8851f05723.png)

**Comment by Rodielm** [comment]
The style of the button has been changed for better visualisation.

**Old Style**
![issue-282-1](https://user-images.githubusercontent.com/10471758/145616606-680d85fe-bab0-418f-bc66-2062fe1b8d5e.png)
![issue-282-2](https://user-images.githubusercontent.com/10471758/145616610-eb72d13c-7fca-4054-9bf4-334e93119d38.png)

**New Style**
![issue-282-4](https://user-images.githubusercontent.com/10471758/145616708-6bf897f1-e178-4cf1-86a1-85773519b9a1.png)
![issue-282-4](https://user-images.githubusercontent.com/10471758/145616739-662eb10f-fd73-47f7-be52-3e5d12f92ec4.png)

**Comment by pamag** [comment]
## Reviewed  ##
The shadow of the buttons has been removed so the problem is solved
