### ISSUE TITLE
Include Settings button to tune the visibility of CTs in Variant Browser  

### ISSUE THREAD

**Issue by antonioaltamura** [opencb/jsorolla#286]
Some users want to customise the visibility of Consequence Types in Variant Browser. At the moment the Settings button doesn't provide a way to "disable" all the filters and show all the Consequence Types (see screenshot 1 and 2). FYI @pamag @imedina .
<img src="https://user-images.githubusercontent.com/6325475/145429911-7623a18b-8465-4ed0-926e-c903b9af651b.png" width=400px>
<img src="https://user-images.githubusercontent.com/6325475/145429915-8b554c68-a182-4b26-8195-a7484e5da529.png" width=400px>

A possible initial solution could be adding an "ALL" button.
![IVA-v2-2-0-dev_CT3](https://user-images.githubusercontent.com/6325475/145431934-0aa3376a-5948-44b0-a3ff-9c745c660adc.png)

**Comment by imedina** [comment]
I think this could be improved by adding a new internal boolean field called `includeAll`, I would prefer not to modify the select items, just disable the checkboxes when `includeAll` is true, this will allow users to momentary select all and then go back to original or saved selection.
Also, this should be a checkbox `Include All` instead of a button.

**Comment by pamag** [comment]
> I think this could be improved by adding a new internal boolean field called `includeAll`, I would prefer not to modify the select items, just disable the checkboxes when `includeAll` is true, this will allow users to momentary select all and then go back to original or saved selection. Also, this should be a checkbox `Include All` instead of a button.

Note for developers: 'include all' is not the same that selecting all transcripts in the list (this list is not a complete set of transcript types).

**Comment by imedina** [comment]
`includeAll` must **deactivate** the filtering so all transcripts will be displayed, and, therefore we do not need to change the current selection as I said before.

**Comment by imedina** [comment]
Just pushed a new version, this looks like this now:

![image](https://user-images.githubusercontent.com/1427327/146698890-ffa88961-70b0-43f4-8dce-8c99f7dc82a8.png)

**Comment by imedina** [comment]
@antonioaltamura you can hide the new section by adding:

`showRefSeq: false`

to the `table` in the browser settings:

![image](https://user-images.githubusercontent.com/1427327/146699493-93be1104-52ad-48dd-98b8-fd5542092313.png)

**Comment by pamag** [comment]
## Reviewed: Still with Issues: ->   closed and create a related ticket https://github.com/opencb/jsorolla/issues/302

**[OK]**  Include all works well igonoring the transcripts slection

**[issue]** "include all" does NOT ignore the gene set selections => if any of them (or both) are disable this transcripts are not shown at all in the VB column "Gene Annotation" but still are in the detailed transcript row for "show all..."

### Reproduce:
1- A variant with all transcript selected
![image](https://user-images.githubusercontent.com/167875/146957869-c6151b69-7c98-484b-a6d9-ee84d84eb6f3.png)


2- Deselect both gene sets and check "select all"
![image](https://user-images.githubusercontent.com/167875/146953247-a3b9ccb7-ed04-409f-8fb1-0d596958b6ea.png)

3- No transcript is shown in the variant row nor in transcript detail view 
![image](https://user-images.githubusercontent.com/167875/146956607-abc98ff1-0036-4582-85be-3331b9d54f26.png)

![image](https://user-images.githubusercontent.com/167875/146956911-35234691-0cea-4fe9-a79f-486d6dc67a92.png)

4- Only shown if clicked in "show all..."
![image](https://user-images.githubusercontent.com/167875/146956130-5d24896e-6320-4533-bbf9-4acf88340c01.png)

![image](https://user-images.githubusercontent.com/167875/146956194-82232315-4ef2-46ee-bf45-5c4214ddee3f.png)
