### ISSUE TITLE
edit interpretation form: dropdown menu is not closed when clicked outside the dropdown

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#290]
## Describe the bug

In the edit interpretation form, after opening a dropdown menu, the only way to close it is or clicking in the top of the dropdown menu or clicking in the header or footer area of the form but not in the main body.

## To Reproduce
![erro_closing_drop-down_menu](https://user-images.githubusercontent.com/167875/146381775-068cd51c-94e7-455f-9d9d-a2d8c9fcf0f7.gif)

**Comment by jmjuanes** [comment]
Unable to reproduce this bug in the current `release-2.2.x` branch (latest commit was aac89e5). Tested in development and latest deployed version:

![Peek 2021-12-20 16-12](https://user-images.githubusercontent.com/5751201/146789573-9be6bbb3-bc36-45ef-a118-3d175b30236e.gif)

Please @pamag, could you verify if the issue persists in the latest docker image of `2.2.0-dev`?

**Comment by pamag** [comment]
## Reveiw
Fixed at some commit before c12bf578b
