### ISSUE TITLE
Fix Review Variant modal

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#294]
## Describe the bug

There are some issues in the variant edit modal.

## To Reproduce

1. Select the **Platinum** study and open the **Case Portal**.
2. Open the **NA12877** case.
3. Open the **Sample Variant Browser**.
4. Click on the **Edit** action of any variant.

## Expected behavior

- Buttons in the modal should be displayed only once.
- We should keep a little padding between the modal border and the left side of the form.

## Screenshots

![image](https://user-images.githubusercontent.com/5751201/146773048-400ae244-801b-4ecc-be58-15495cc538a7.png)

**Comment by jmjuanes** [comment]
Fixed variant review modal in commit b62cc0c and applied minor UI changes in the modal buttons in commit f6bea02:

![image](https://user-images.githubusercontent.com/5751201/147085106-0aa7046c-6109-4ab3-adf8-64a4d3a86ab4.png)

**Comment by pamag** [comment]
## Reviewed

FIXED
