### ISSUE TITLE
Allow to search cases by names that contains the specified characters

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#297]
## Description

Currently, the case search box can only retrieve cases that **start with** the characters introduced in the search box. 

![Peek 2021-12-20 19-48](https://user-images.githubusercontent.com/5751201/146817625-f7337a59-577f-4456-ba2e-e6cd28da9c55.gif)

But **OpenCGA** allows using regular expressions to search for example by `id` (see opencb/opencga#1812):

1. contains:  `name =~ /pepe/i`
2. starts with: `name =~ /^pepe/i`
3. ends with: `name =~ /pepe$/i`

## Proposed improvement

Update all `*-autocomplete.js` components to allow searching using a regular expression.

**Comment by jmjuanes** [comment]
Implemented for the Case Analysis ID in commit fcb7d55: 

https://github.com/opencb/jsorolla/blob/fcb7d55a26eb4f4ae55d575bc357b1695ab6796e/src/webcomponents/commons/filters/clinical-analysis-id-autocomplete.js#L69

![Peek 2021-12-21 17-29](https://user-images.githubusercontent.com/5751201/146964978-f868ec04-df4f-4c61-871b-d5548d5924f2.gif)

**Comment by jmjuanes** [comment]
Now all `*-autocomplete.js` components allow searching by contains, starts with and ends with: 

![Peek 2021-12-21 18-34](https://user-images.githubusercontent.com/5751201/146973810-5b435c9a-cb16-4e82-82e4-2f76f0d53fad.gif)

**Comment by pamag** [comment]
## Reviewed
DONE
