### ISSUE TITLE
question: are there any instructions on how to build (production-ready) jsrolla?

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/jsorolla#30]
i've tried building the next-v2.0.0 branch with grunt but it fails SyntaxError:

```
Running "uglify:dist" (uglify) task
JS_Parse_Error {
  message: 'SyntaxError: Unexpected token: name (CellBaseAdapter)',
  filename: 'lib.js',
  line: 19824,
  col: 6,
  pos: 787923,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (jsorolla/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (jsorolla/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (jsorolla/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
...
>> Uglifying source build/2.0.0-beta/lib.js failed.
Warning: Uglification failed.
SyntaxError: Unexpected token: name (CellBaseAdapter). 
Line 19824 in build/2.0.0-beta/lib.js
 Use --force to continue.

```

**Comment by mbsimonovic** [comment]
hm, seems like grunt is not happy with es6 class declaration (class CellBaseAdapter)

**Comment by imedina** [comment]
Sorry for the late response, I have created a new README and add instructions to build jsorolla. As you can see in #38 and #54 we have removed both bower and grunt as dependencies and migrated to npm.

Now to build the demos you just need to run: `npm run build`

To use JSorolla as dependency you have to build the libs with  `npm run dist`. This will create the a dist folder with all javascript concatenated and minimised, inclujding es6 code. You only need to import core.min.js and genome-browser.min.js.

Also, I'm tagging 2.0.0-rc release in a couple of days and deploying in npm. Documentation and tutorials will be added next week.
