### ISSUE TITLE
Panel links are lost after updating the case

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#300]
## Describe the bug

After updating a case, the panel links are lost in the interpretation manager section.

## To Reproduce

1. Go to **Case Portal** in the **Platinum** study.
2. Open the **NA12877** case.
3. In the **Interpretation Manager** tab, the disease panels have links that open a new tab with the panel information.
4. Go back to the **Case Manager** and update the case (for example lock the case).
5. Open the **Interpretation Manager** tab. Panel links are lost.

## Expected behavior

Disease panels must have a clickable link after updating the case.

## Screenshots

![ezgif-6-656b099d20](https://user-images.githubusercontent.com/5751201/146923534-1cf67bee-658a-4192-a498-fe546b4ec953.gif)

## Additional tasks

- [ ] Display also the panel version (if provided).

**Comment by imedina** [comment]
This is because a small bug in OpenCGA, it should be already fixed

**Comment by pamag** [comment]
## reviewed
> This is because a small bug in OpenCGA, it should be already fixed

jsorolla commit 4f8dbe4c2eedc15edf987bc30eaa8f52a851b939
still the isse is present.

**Comment by pamag** [comment]
## Reviewed

FIXED in 
jsorolla 1f47fb24a338c4159d2b075a3eaf3e2877b7340d
opencga  eb7dce7a68d93027ee9dbbe987b1c8e715f3f906
