### ISSUE TITLE
Bug: doesn't display result when searching again with the same value

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#301]
## Description

At the moment, all Autocomplete from Admin has the issue that doesn't display result when searching again the same value.

**Unexpected Result**

![Peek 2021-12-21 14-09](https://user-images.githubusercontent.com/10471758/146938661-f019dfe9-4e54-436a-ad4e-84b981bab133.gif)

**Expected Result**

Display the result even if the value is the same.

-  Check if the result has data or not.
-  In case the result is empty, then consume the service.
-  In case the result has data, then compare the search value with the results before consuming the service.

**Comment by pamag** [comment]
## Reviewed

commit: f104bd4712825f4c4fdc278c088a4b7b7bff1bf0

FIXED
