### ISSUE TITLE
Unable to create new interpretations: status.id not marked as ignorable

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#304]
## Describe the bug

commit: f6bea023104151cf7a24ffa94c620aea8fdd23de

When creating a new interpretation an error is raised:

![image](https://user-images.githubusercontent.com/167875/147103652-dfd3a3f6-0243-41a0-9983-cf417906a729.png)

**Comment by jmjuanes** [comment]
Fixed bug in commit dabb4be: the field `status.id` was processed as `interpretation["status.id"]` instead of `interpreation.status.id`. Now working as expected: 

![Peek 2021-12-22 16-28](https://user-images.githubusercontent.com/5751201/147116390-318e52e8-3cc7-4fb2-bd30-fd678ccd483e.gif)

**Comment by pamag** [comment]
## Reviewed
OK
