### ISSUE TITLE
 interpretation_id in CREATE INTERPRETATION should be renamed to case_id, also add TAG field and add comment about that interpretation ID is automatic now

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#305]
## Describe the bug
When creating an interpretation, in the create form would be better to have the field "Case ID" instead "Interpretation ID"
(as the value is the case_id). The interpretation ID will be created automatically on saving the form.

![image](https://user-images.githubusercontent.com/167875/149749427-9df9aee0-258c-4512-b461-91c19bc20517.png)

- [x] 1- The id of the interpretation is assigned automatically, so here instead of the interpretation id would be better to have the **CASE_ID** on creation (warning: in the interpreation EDIT it sould be "InterpretationID", so they are different forms)

- [x] 2- Add a TAG for the comments in the form

## Related

 #375

**Comment by Rodielm** [comment]
Fixed  e1ecc1b

![image](https://user-images.githubusercontent.com/10471758/151217839-b1e8f9eb-2ac6-4be3-8987-67db25998d75.png)

**Comment by pamag** [comment]
## Reviewed

commit e1ecc1b84d3d7876cd274a21d529200bf9a381ac

FIXED
