### ISSUE TITLE
due date in case manager is not stored 

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#309]
## Describe the bug

- [x] (1) Case manager form: Due date input is not detected as changed when adding the date so the button update does not work

![unable_to_update_date_in_case](https://user-images.githubusercontent.com/167875/147175602-9e18ebe0-f769-48ea-abc1-46cf82406cbf.gif)

- [x] (2) Also in the case portal the case has a due date but in the case manager this due date is missing

![due_date_in_case_portal_but_not_in_case_manager](https://user-images.githubusercontent.com/167875/147175608-8b2b7292-31eb-41ea-9a99-511516befb62.gif)

- [x] (3) if we manage to update the case with a new due date (updating also another field to activate the upate button) the new due date is not stored

 ![upddate_date_in_case_manager_does_not_work](https://user-images.githubusercontent.com/167875/147175618-782d48e4-9ac6-4cc6-95ec-fadd67ebd042.gif)

**Comment by jmjuanes** [comment]
Fixed date picker in commits 71f1396, ce33828 and 0e8e820: 

![Peek 2021-12-23 15-37](https://user-images.githubusercontent.com/5751201/147255693-6ce4fedf-0676-4aa7-a15e-b4c7d45793a5.gif)

**Comment by pamag** [comment]
## Reviewed
commit 905480934bab2042035f1112de49bec57bb1ab2f

DONE
