### ISSUE TITLE
Sample atribute in case create fixes: initial value, restrict to vcf, <br> elements

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#312]
## Describe bug
Some issues in sample attribute in `create case` form: 
- [x] (1) samples data is a string with unprocessed `<br>`
- [x] (2) sample should be a list with only VCF (there are png and other files)
![image](https://user-images.githubusercontent.com/167875/147368973-254f5fa0-5254-4ad1-8bd8-d2575f6b2a2e.png)

- [x] (3) Samples should be retrieved after the proband has been added (at the moment raise an error trying to retrieve samples for no proband)

![image](https://user-images.githubusercontent.com/167875/147369092-66f52427-e3c0-4cd8-b855-cb7119be5d22.png)

**Comment by Rodielm** [comment]
`samples`:   display a message until the user select a proband.

![clinicalCreate](https://user-images.githubusercontent.com/10471758/147369568-2cfde16a-62e8-4ef8-933a-c8a106a1c0c4.gif)

sample only show VCFs

![image](https://user-images.githubusercontent.com/10471758/147370039-a637252e-a407-4763-a0a4-63f47aceed2e.png)

**Comment by pamag** [comment]
## Reviewed

Fixed with a minor issue: the files list is concatenated by spaces and should be better to have it as new lines.
![image](https://user-images.githubusercontent.com/167875/147469689-c20c3c6b-2346-4aeb-a9db-2050f611b6e8.png)

Closing ticket and opening a new one for the "sample files listed one per line" https://github.com/opencb/jsorolla/issues/313
