### ISSUE TITLE
Panel lock in Case Manager: add a message explaining why it is disabled 

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#316]
## Improvement description

When a case has several interpretations with different disease panels and some of them are not in the original disease panel of the case, the `Disease panel lock` slider is disabled. 
![image](https://user-images.githubusercontent.com/167875/147579269-8576d5a0-2b05-4179-999f-163c5a3314bc.png)

**ACTION**: Add a message explaining why it is disabled
```

```

**TODO**:  decide the message text

**Comment by imedina** [comment]
@pamag take a look at this:

![image](https://user-images.githubusercontent.com/1427327/158504802-be406f41-b0b4-4651-a0df-b498e7bca87c.png)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        58c76ae9a5
    IVA commit:
        a100ebd81423c38600013acd98a51e14a7b51309

FIXED with minor comment:
@imedina work as intended but, if a case with only one interpretation with the right panel, is locked, then the panel is disabled and the message about "all interpretations should have the same panel" appears. This is not totally right but is a minor issue.

![panel_lock-when_case_lock-info 2022-03-16 17-45](https://user-images.githubusercontent.com/167875/158644392-42c4bdd1-31ec-4383-9240-78eae92f8186.gif)

**Comment by pamag** [comment]
Moved to 2.3  https://app.clickup.com/t/36631768/TASK-481
