### ISSUE TITLE
Deleting a case has UX issues: focus at bottom of the page, return to default row number.

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#320]
## Describe the bug

- [x] (1) when the user has the case portal with not a default number of rows (25 here) after deleting a case the view is focused at the bottom of the page and the table is displayed with only the default rows and lost pagination.

![deleting_a_case_ux_issues](https://user-images.githubusercontent.com/167875/147694322-b01a3554-1177-4f0f-a5a6-8a690de65392.gif)

**Comment by Rodielm** [comment]
## Description

The reason why this problem occurs is that this line:
https://github.com/opencb/jsorolla/blob/51f85da2dec1f4de8e1867143e74ba6644888a86/src/webcomponents/clinical/clinical-analysis-grid.js#L89

The table is destroyed, and a new table is created, so the page scrolls down (at this point the table has been destroyed). At this point the table no longer exists, and then it is recreated with a new state, so it returns to the initial page of the table.

## Solution

It is not necessary to destroy the table, it has a feature to delete a row without recreating a new table. So it allows you to use keep the same state, the same pagination before and after deleting the row. https://github.com/opencb/jsorolla/commit/718c5d3be5ea366d7be7fdadefca7f4c5875186d

**Comment by pamag** [comment]
## Reviewed
commit ba24b4d15c4ea37b8349c83346a755300303e499
Done
