### ISSUE TITLE
Removing filter "disease panel" should auotomatically remove "panelModelOfInheritance" filter

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#323]
## Describe a bug

If we have a disease panel filter and a panelModeOfInheritance filter. If the "disease panel" filter is removed an error is raised.
![image](https://user-images.githubusercontent.com/167875/147794350-6bf6df7a-7663-4b59-8cdc-0f72f9f070b6.png)

**Comment by Rodielm** [comment]
If the disease panel is deleted, the other sub-filters are deleted.

![varianBrowserFilters](https://user-images.githubusercontent.com/10471758/148845188-739ce628-9ec9-4d2a-bea6-465f7eb8fdfa.gif)

**Comment by pamag** [comment]
## Reviewed

FIXED
