### ISSUE TITLE
Improve variant evidence edit form in variant browser 

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#329]
## Feature improvement description

In the Variant Browser the edit of the variant subrow for clinical_evidence needs to be changed

### Current view:
![image](https://user-images.githubusercontent.com/167875/148938310-49a26300-80fa-4699-a7e5-afaca2c4bff2.png)

### Canges:

The edit form needs to allow the update of the fields:
- ACMG
- TIER
- clinical significance (will be shown in the ACMG column, like in the automatic prediction column)

**Comment by pamag** [comment]
note: in current model the discussion is called justification and needs to be changed to discussion.

**Comment by jmjuanes** [comment]
New clinical evidence review model:

```

```

**Comment by jmjuanes** [comment]
Migrate to new review model and added Clinical Significance dropdown to the evidence review modal in commit 086a1a2: 

![image](https://user-images.githubusercontent.com/5751201/149005235-8b9a328d-8b2f-4660-a4f5-ae6d375216b6.png)

**Comment by jmjuanes** [comment]
Evidence can be reviewed only if the variant and the evidence are selected: 

![Peek 2022-01-11 21-38](https://user-images.githubusercontent.com/5751201/149018520-fc0655fa-5ff5-4d61-9aac-9990ce2cf48c.gif)

**Comment by jmjuanes** [comment]
Added **Updated variants** to the save section in the variant interpreter browser: 

![image](https://user-images.githubusercontent.com/5751201/149145099-e2a7c95e-5ae6-4a49-9b8d-6652fa8c76ba.png)

**Comment by pamag** [comment]
Added dropdown menu for ACMG
![image](https://user-images.githubusercontent.com/167875/149294079-08835863-eabb-4aa7-aff6-20e7ae7bacab.png)

**Comment by pamag** [comment]
## Reviewed

commit: 6ddc3a6fb49a40af503fa98a38ec19258b3ed7d1

FIXED
