### ISSUE TITLE
Panels are not displayed in Case Manager summary

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#333]
## Bug description

In a case, the panel is not displayed in the summary section. This only happens when the selected panel is a custom panel (not from PanelApp).

## Screenshots

Panel is selected in the **Disease Panels** dropdown but not displayed in the summary section: 

![image](https://user-images.githubusercontent.com/5751201/149120447-6563cc40-5394-4eb2-84b4-29839d35736f.png)

**Comment by jmjuanes** [comment]
Fixed this small bug in commit 7ad059e. Now custom panels are displayed as expected.

**Comment by pamag** [comment]
## Reviewed

Fixed
