### ISSUE TITLE
Disease panels are not marked as updated when updating an interpretation

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#339]
## Describe the bug

The disease panels select is not marked as updated (with an orange border) in the **Edit Interpretation** modal.

## To Reproduce

1. Go to Case Portal and open the case **NA12877** in the **Platinum** study.
2. Click on **Interpretation Manager** tab.
3. Click on **Edit Interpretation** of any interpretation.
4. In the **Disease panels** select, add or remove a panel. The dropdown is not marked as updated.

## Expected behavior

The select element should be marked as updated (with an orange border) when we add or remove a disease panel.

## Screenshots

![Peek 2022-01-13 16-27](https://user-images.githubusercontent.com/5751201/149358999-afc53087-0957-463f-90e3-f042bd03d574.gif)

**Comment by jmjuanes** [comment]
Fixed in commit f06e6f4 for the **disease panels** field and for the **status** field:

![image](https://user-images.githubusercontent.com/5751201/149363566-b148ede4-896a-4db8-b1e7-269ce3f2462e.png)

**Comment by pamag** [comment]
## Reviewed
commit: 6ddc3a6fb49a40af503fa98a38ec19258b3ed7d1

FIXED
