### ISSUE TITLE
bug: jsrolla doesnt work in IE < Edge

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/jsorolla#34]
(tried this on branch next-v2.0.0), the console says:

<img width="500" alt="e47363de-0dba-11e7-8868-a3253a0925d4" src="https://cloud.githubusercontent.com/assets/888008/24525991/c8579050-159c-11e7-8f66-20e80de35f1a.png">

the line calls: wrap(e["import"]), and seems like it comes from bower/webcomponents.

Turns out it's a known bug: [https://github.com/webcomponents/webcomponentsjs/issues/529](https://github.com/webcomponents/webcomponentsjs/issues/529), jso-table.html has a div with id="wrap" :) the fix is simple, just change "wrap" to anything else.

**Comment by agaor** [comment]
This issue is fixed on April 4.
