### ISSUE TITLE
Comment and tag not saved in EDIT interpretation

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#349]
## Describe the bug

When editing an interpretation, the comment and the tag are not updated

![image](https://user-images.githubusercontent.com/167875/149822408-8cc2b12b-f6dd-4656-8f75-9094bf0efec3.png)

## Related
https://github.com/opencb/jsorolla/issues/305

**Comment by Rodielm** [comment]
I found another bug when I was fixing this.

It's fixed too. https://github.com/opencb/jsorolla/commit/73fa370d8ccd58f91138b6f5741a5f4260d17d5c#diff-fa55166ca7408ec45411948b839e4d0476ef8def7cfbc0f5aebac58e6fbb8abdR92
![CommentIssue](https://user-images.githubusercontent.com/10471758/151184403-8f6346c0-2ebe-4069-b4e7-d60571945e04.gif)

**Comment by pamag** [comment]
## Reviewed

commit 958d4efa5e3db01bade515cd448906fa53ee041c

FIXED
