### ISSUE TITLE
Change extensions and the filename conventions in downloaded files from the grids

### ISSUE THREAD

**Issue by antonioaltamura** [opencb/jsorolla#354]
The extension of the file the users download should be changed from ".txt" to ".tsv", for clarity and to let the users open them more easily in Office/Libreoffice.
Also, there is no consistency in filenames when you download a TSV or JSON file.
In some grids the filename is `<studyFQN>.txt` in some other `<entityName>_<studyFQN>.txt`, and some other have other forms.

This would involve a small change in all download functions across the application.

**Comment by pamag** [comment]
@antonioaltamura please consider also this suggestion for the export names when exporting interpretations https://github.com/opencb/jsorolla/issues/303
