### ISSUE TITLE
Change ERROR message for a warning about not finding variants after aplying a filter

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#356]
## Describe the improvement

When a filter returns no variants, 

instead of:
-- ERROR: no valid variant or annotation

change to:
-- Warning: there are no variants or annotations for the current filter

(follow same steps as in https://github.com/opencb/jsorolla/issues/230)

![image](https://user-images.githubusercontent.com/167875/150257004-cb0cad8b-9ddb-4c34-8dc1-c08225374483.png)

**Comment by imedina** [comment]
@pamag is this not the same ticket as #236 ?

**Comment by pamag** [comment]
## Reviewed

![image](https://user-images.githubusercontent.com/167875/150487586-31eced77-00c7-46f9-97a8-50fbc0a155be.png)

Note: Here as it is a filter action we leave the grid with a message about not variants found (so we know there was no error). This is slightly different to issue
in #230 (primary interpretation), there the solution was different: if no variants in primary interpretation is OK not to show the grid as it is not a filter action but a summary display so we show nothing (only a warning to leave clear that the No-grid is intentional and not due to an error)
