### ISSUE TITLE
Pedigree drawing fails

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#357]
## Description

In the summary section of the family browser after clicking in a family, the pedigree is not rendered as expected and the sex field if each member of the family displays a `[object Object]` value instead of the correct sex.

## To reproduce

1. Open **Ashkenazim Trio** study.
2. Navigate to **Family Browser**.
3. Click in the first family (`ashkenazim_trio`).
4. Scroll down to the family summary.

## Screenshots

![image](https://user-images.githubusercontent.com/167875/150309678-c4a9a476-1170-4518-9ae1-3af4375e6195.png)

## Additional context

This issue may be related to #327 and changes made in the **Sex** field of the Individual model in OpenCGA opencb/opencga#1855.

**Comment by jmjuanes** [comment]
- Fixed displaying sex field in family members table and added compatibility for old OpenCGA versions in commit fe123be.
- Fixed sex field in family members for generating the pedigree in commit db14fed.

![image](https://user-images.githubusercontent.com/5751201/150330085-8c7dfc44-cae3-4107-a9fe-20e1cb4c56e5.png)

**Comment by pamag** [comment]
## Reviewed

commit: f104bd4712825f4c4fdc278c088a4b7b7bff1bf0

FIXED
