### ISSUE TITLE
Sample Genotype rendered as allele_frequency: the 0 AF allele still shows area (cell borders)

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#363]
## Describe the bug

When rendering the allele frequencies, the 0 AF color area still is remanent (the cell borders)

![image](https://user-images.githubusercontent.com/167875/150719967-21de25f1-ec3a-4aa1-ba58-f8dd49f144a0.png)

## Expected behavior

Zero area for 0 AF allele 

![image](https://user-images.githubusercontent.com/167875/150720003-eecf4d5b-fa11-4e72-97ac-e0e72eae8402.png)

**Comment by imedina** [comment]
@pamag This is not fixed, please review:

![image](https://user-images.githubusercontent.com/1427327/158501537-fc387be1-6ecc-40b9-89b5-99bf66f93f53.png)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        58c76ae9a5
    IVA commit:
        a100ebd81423c38600013acd98a51e14a7b51309


FIXED
