### ISSUE TITLE
Sex is not displayed in the sample genotypes filter for family

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#366]
## Describe the bug

The sex field is not displayed in the sample genotypes filter for a family.

## To Reproduce

1. Go to **Case Portal** and select the **Ashkenazim Trio** study.
2. Open a family case.
3. Go to **Sample variant browser** step.
4. Click on **Sample Genotype Filter** button at the left side.

## Expected behavior

Correct proband sex should be displayed.

## Screenshots

![image](https://user-images.githubusercontent.com/5751201/150772876-d131a50b-2422-48e7-92cf-28a59796b418.png)

## Additional context

This issue may be related to #327, #357 and changes made in the **Sex** field of the Individual model in OpenCGA opencb/opencga#1855.

**Comment by jmjuanes** [comment]
Fixed sex displayed value in commit a7f8520 and sex icon in commit 170cb7c.

![image](https://user-images.githubusercontent.com/5751201/150778684-0ac7e7c8-8140-4684-bf49-07329d20dcbd.png)

**Comment by pamag** [comment]
## Reviewed

commit: 170cb7c9b1a893debc598949d76234359836b08a

FIXED
