### ISSUE TITLE
Members field in Case Create for Family needs to be updated for SEX datamodel as object

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#367]
## Describe the bug

Members field in Create Case for family is still using SEX as a string instead of as an object.

![image](https://user-images.githubusercontent.com/167875/150952449-9ae4f35f-5c3f-42cf-b523-6a35ce688033.png)

## Reproduce the bug

- Go to Case Portal
- New case
- Select Analysis Type: Family
- Section Family Analysis Configuration
  - Members

**Comment by jmjuanes** [comment]
Fixed in commit a5f8312:

![image](https://user-images.githubusercontent.com/5751201/150962927-0c58594f-17e9-4b1e-843e-f2a62334bcb0.png)

**Comment by pamag** [comment]
## Reviewed

commit: a5f8312fcb0276230f19c18c29963dbfebbfc9fa

FIXED
