### ISSUE TITLE
CLEAR button in CREATE_INTERPRETATION discard the form instead clearing the inputs

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#370]
## Describe the bug

In create interpretation form, the button CLEAR closes the form. 
![image](https://user-images.githubusercontent.com/167875/151138133-5116243d-ff15-410b-881b-35d0e4ff35e4.png)

## Proposed fix

- [ ] CLEAR button should only clear the form and leave in its default state
- [ ] we need a DISCARD button

**Comment by Rodielm** [comment]
It is a typo, the text should be `cancel`. not `clear`, if the button is in the modal the action is to close the modal. However, let's consider the `clear` button for the modal form later.

- [ ] renamed `clear` to `cancel`

**Comment by Rodielm** [comment]
Fixed 87000e0

**Create Interpretation**
![image](https://user-images.githubusercontent.com/10471758/151524583-bedc7bc1-6ebd-4bcd-a19d-ceaeaee64277.png)
**Edit Interpretation**
![image](https://user-images.githubusercontent.com/10471758/151524640-1b8aafbc-ee52-40c5-84a8-e25fc7ee367d.png)

**Comment by pamag** [comment]
## Reviewed

commit 958d4efa5e3db01bade515cd448906fa53ee041c

FIXED
