### ISSUE TITLE
Display data-form content in tabs or vertical pills

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#371]
## Description

In some forms (for example in the Variant Browser settings modal) we need to display a large number of options and fields. It would be nice to group form sections into tabs or pills.

## Proposed solution

Add a new type to `data-form` to display the content grouped into tabs or pills. The `type` field of the data-form configuration will accept two new values:

- `tabs`: for displaying form content grouped into a classic tabbed interface. Example:

![image](https://user-images.githubusercontent.com/5751201/151152250-faa21379-9873-450e-85a8-0b90f2226175.png)

- `pills`: similar to the tabs, but the navigation will be placed at the left side of the form content and will implement a pills interface. Example:

![image](https://user-images.githubusercontent.com/5751201/151152204-bb6219ae-0536-4291-afeb-8deb68562de0.png)

## Additional context

This issue is related to #268 (data-form redesign) and #369 (displaying conditional formatting option in VB settings form).

In the future, we could also configure if pills will be placed at the left or right side of the form content adding a new `pillsPosition` parameter:

```
{
    type: "pills",
    display: {
        pillsPosition: "right",
    },
}
```

Images source: https://getbootstrap.com/docs/5.1/components/navs-tabs/#javascript-behavior

**Comment by jmjuanes** [comment]
Added tabs type to data-form for displaying sections grouped into tabs in commit 2ff1cb9: 

![image](https://user-images.githubusercontent.com/5751201/153867933-2d7be467-8034-40e5-8a05-efcec5fba015.png)

**Comment by pamag** [comment]
## Reviewed

IVA commit: 6df12c6cdc47629a3b362fe8150c53debfb501e2 
OpenCGA commit: bcbe75e68198a1171ad977e747189ddcdbc74c39

FIXED
