### ISSUE TITLE
Adapt for using CellBase 5.0

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#372]
## Description

In CellBase 5.0 the endpoint `starts_with` has been renamed to `startsWith`, so components that are using the old endpoint will not work with CellBase 5.0. 

## Affected components 

There is only one component in jsorolla that is using this webservice: 

https://github.com/opencb/jsorolla/blob/7f8a5e950b7ff4019a9d4aff80544d346368cce8/src/webcomponents/commons/filters/feature-filter.js#L98-L104 

This component is used for filtering by Gene in the Variant Browser: 

![image](https://user-images.githubusercontent.com/5751201/151229227-6d19e368-a467-43f3-8dc4-2c2be929164f.png)

**Comment by jmjuanes** [comment]
Added version check in `feature-filter` in commit 3e113cd: we will call the new endpoint (using `startsWith`) if CellBase version is `v5`, and the old endpoint (using `starts_with`) if CellBase version is not `v5`.

- [X] Tested with CellBase v4.

- [X] Tested with CellBase v5.

**Comment by jmjuanes** [comment]
Fixed wrong subcategory in commit 3682e56: using `gene` instead of `id`.

https://github.com/opencb/jsorolla/blob/3682e5626b02bbc0cd018cdaea5fa86a359d7eba/src/webcomponents/commons/filters/feature-filter.js#L101

**Comment by pamag** [comment]
## Reviewed

FIXED
