### ISSUE TITLE
Feat: Add "footnote" or note to data-form

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#374]
## Description

![image](https://user-images.githubusercontent.com/10471758/152199928-ddcb196a-995d-4f9c-91c0-e9c49fef2a37.png)

Allow the data form to add an instruction message or a note to the form in general. This way, the user will be sure how to fill in the form or know the instructions.

**Structure**

``` js
{
    title: "",
    type: "notification",
    text: "Empty, create a new phenotype",
    display: {
        visible: sample => !(sample?.phenotypes && sample?.phenotypes.length > 0),
        notificationType: "info",
    }
}
....

```

**Comment by pamag** [comment]
## Reviewed

commit 122f092ad6c7d1ddaec064ff5eaac7fb291b4095

FIXED
