### ISSUE TITLE
create a note about the interpreation ID being created automatically

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#375]
## Description
Add a general note to the interpretation-create form.

![image](https://user-images.githubusercontent.com/10471758/151195429-ab2cdb33-0ee4-49d2-9262-4daf6aaae865.png)

**Comment by Rodielm** [comment]
Added the note 32a3664
![image](https://user-images.githubusercontent.com/10471758/152157076-30b0172d-c4a4-493f-8501-d80eda309ef1.png)

**Comment by pamag** [comment]
## Reviewed
commit 32a3664944003d09d3ac129b9946c3f8aafc115f
FIXED
