### ISSUE TITLE
Selection in Consequence Type filter is lost after searching in VB

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#376]
## Describe the bug

In the **Variant Browser**, after selecting some consequence types using the checkboxes and clicking in **Search** button, the selection is lost (terms checkboxes are automatically unchecked).

## To Reproduce

1. Go to Variant Browser.
2. Expane the **Consequence Type** filter.
3. Check some preset terms.
4. Click on **Search** button.

## Expected behavior

Selection should remain checked after clicking in **Search** button.

## Screenshots

![Peek 2022-01-26 18-13](https://user-images.githubusercontent.com/5751201/151213706-7cee0b66-f04f-4bdc-a4a8-b3cf8c899dff.gif)

## Additional context

~~This bug only happens in the **Variant Browser**. In other browsers like **Sample Variant Browser** works as expected.~~

**UPDATE**: after fixing a minor bug updating the query in the **Sample Variant Browser**, the selection is also lost in this browser. See comment https://github.com/opencb/jsorolla/issues/376#issuecomment-1023141670

**Comment by jmjuanes** [comment]
After exploring why in the **Sample Variant Browser** the selection remains after the **Search** button is clicked, found that this browser is not updating the query stored in an internal variable called `this.query`: 

![Peek 2022-01-27 12-59](https://user-images.githubusercontent.com/5751201/151355010-49a7150c-9e93-4681-aec9-71f3b9ea70c1.gif)

After fixing this bug in commit fde2470, **the consequence type selection is also lost**: 

![Peek 2022-01-27 13-05](https://user-images.githubusercontent.com/5751201/151355674-29bb149f-8c9f-4198-b2f7-e20c6b09aff4.gif)

**Comment by jmjuanes** [comment]
Fixed in commit cc96b27 (original commit was 7cfe656 but I added the wrong issue commit). 

Working in **Variant Browser**:

![Peek 2022-01-27 13-19](https://user-images.githubusercontent.com/5751201/151359059-08bb1ce1-0d61-4bd6-856c-bff94ffe9855.gif)

Working in **Sample Variant Browser (RD)**:

![Peek 2022-01-27 13-20](https://user-images.githubusercontent.com/5751201/151359085-f8720190-d861-46f2-93d1-aa84a6736925.gif)

**Comment by jmjuanes** [comment]
After the review session, we agreed to revert the behavior added in commit 7cfe656, so now:

- If a preset is checked, this check remains active after clicking on the **Search** button.
- If we manually remove a term of a selected preset and add it again, the preset checkbox will remain unchecked.

Added a note in commit 383bfb7.

**Comment by pamag** [comment]
## Reviewed

commit 958d4efa5e3db01bade515cd448906fa53ee041c


FIXED with NOTE:
The initial issue has been fixed but  found a new issue after fixing this issue https://github.com/opencb/jsorolla/issues/382
