### ISSUE TITLE
TypeError pop up in the Variant Browser

### ISSUE THREAD

**Issue by Rodielm** [opencb/jsorolla#377]
## Description

The variant browser displays an error when trying to consume an ebi service.

![image](https://user-images.githubusercontent.com/10471758/151278433-2cb248b8-b87f-4114-bee9-b39b7b66b450.png)

seems to have occurred in the `variant-modal-ontology` component
![image](https://user-images.githubusercontent.com/10471758/151278470-d1481752-d097-4ea5-a12f-42830b186842.png)

### Possible Cause
![image](https://user-images.githubusercontent.com/10471758/151278548-ff9c7452-4fc1-437d-b699-cbb7fbc7ed78.png)

**Comment by imedina** [comment]
This was an issue with EBI REST web service, closing this issue
