### ISSUE TITLE
Some images are not displayed

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#380]
## Describe the bug

In some sections, for example in the **ASCAT Metrics** section of the **Quality Control Overview** step of the Case Interpreter, not all images are displayed.

## To Reproduce

1. Select the **test** study of the **Cancer GRCh37** project.
2. Open the **Case Portal** and click on the first cancer case.
3. Click on the **Quality Control** step and then click on the **ASCAT Metrics** in the left side menu.
4. The first image from the **ASCAT QC PLOTS** is not displayed.

## Expected behavior

All images should be displayed.

## Screenshots

![image](https://user-images.githubusercontent.com/5751201/151389924-52e4e8a3-8e2d-4248-9f97-7389841dcbed.png)

**Comment by imedina** [comment]
@jmjuanes well done! closing it!
