### ISSUE TITLE
Software error message is shown when filtering by genes not in the DB

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#386]
## Describe the bug

Filtering by a non existing gene shows a software ERROR instead a user message and zero rows.

```
VariantQueryException: Malformed "gene" query : "brca". Gene not found!
```

Needs the GENE NOT FOUND warning, but the "variantQueryException" is not necessary

![image](https://user-images.githubusercontent.com/167875/151236310-01de5a8a-1e51-4577-96af-2931e25e1bf5.png)

**Comment by imedina** [comment]
User error message will be improved in OpenCGA
