### ISSUE TITLE
Option to have specific copy templates pre configured by the user

### ISSUE THREAD

**Issue by halender** [opencb/jsorolla#391]
### Motivation:

Some user teams use a spreadsheet for examining variants and eventually produce the reports. This spreadsheet have their own internal defined schemas.

They would like to be able to:

*   Copy the variant info from IVA and paste to their documents with their own schemas.
*   Export a file (spreadsheet, txt,…) from selected variants in IVA using their own schemas.

### Technical Solution:

*   Configuration of copy functions and the fields (schemas) to be copied at JavaScript module settings level. Nice to have 2 by default copies schemas preconfigured.

//Sample configuration copies: [ { name: "Name of the Schema", description: "Description of the Schema", copy: variant=>

 { //All the fields defined by the own user team schema. For instance: return variant.id; } 

} ]

*   A “Copy button” per variant row on IVA->Case Interpreter->Interpretation Review->Primary Findings (with the selected variants) to select wich “schema” used for copy current variant info to clipboard.

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/35806821/151974586-51a5aff6-af5a-486c-9aff-c6fbf429f1ac.png)</span>](https://user-images.githubusercontent.com/35806821/151974586-51a5aff6-af5a-486c-9aff-c6fbf429f1ac.png)

*   Include All the Copies configurations as an option for “Export”:

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/35806821/151974657-1bcac156-0ec9-4145-865d-17c6c254c2c6.png)</span>](https://user-images.githubusercontent.com/35806821/151974657-1bcac156-0ec9-4145-865d-17c6c254c2c6.png)

┆<font color="#707070">Issue is synchronized with a [Clickup task](https://app.clickup.com/t/2bmgquu) by [Unito](https://www.unito.io)</font>

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        8970ea3095a741596beed9b6f97752edf1ee007d
    IVA commit:
        f56392553afdcc02f3c01a71bb1e1fdeed39f962


![image](https://user-images.githubusercontent.com/167875/154868544-52177c4c-ad38-4b44-8f80-6c9432434af1.png)

### PASS
- [x] seq actions links resolves correctly
  - [x] copy JSON
  - [x] download JSON   

### FAIL
- [ ] Download JSON has a problem with the file name -> It should use the new template. 

![image](https://user-images.githubusercontent.com/167875/154868498-c95098cb-b0aa-4e8e-8b14-0a9e4add31fc.png)

### Minor issues

Actions dropdown in variant rows in SBV need not to be confined by the table area. If only one or two rows are present, the full dropdown is not showed

![png_2905656804277671911](https://user-images.githubusercontent.com/167875/154940388-cad7e817-3941-477e-a460-422090071293.png)
