### ISSUE TITLE
Case Download action in Case Portal retrieve all cases instead only its case

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#395]
## Describe the bug

Action `Download` in a case downloads ALL the cases, instead of only the data from a case.

It is doing the same that the Download at the top of the grid.

![image](https://user-images.githubusercontent.com/167875/152012537-ed34836d-71a4-456f-a540-80e39ace5291.png)

## How to reproduce the bug

1- Go to case portal, 
2- Click in actions from a case and select Download

![image](https://user-images.githubusercontent.com/167875/151990208-cb6a2b4f-7a89-45cc-ba88-80661e2235e0.png)

3- The JSON contains all the cases

![image](https://user-images.githubusercontent.com/167875/152011334-42daaede-829d-48d3-97b0-6abc67f18bc9.png)

**Comment by pamag** [comment]
Note: this bug was introduced in the commit  fixing this issue https://github.com/opencb/jsorolla/issues/393

**Comment by pamag** [comment]
## Reviewed

FIXED the JSON content BUT still the name of the proposed file is the study name not the case name

moved to "in progress" with a pending task
- [ ] The filename to download should be named after the case, not the study. And it would be very useful to also append the download date

**Comment by halender** [comment]
Already changed this, @pamag . Could you test it and close the ticket?

**Comment by pamag** [comment]
## Reviewed

Fixed the name 

![image](https://user-images.githubusercontent.com/167875/158431913-55402079-1fce-475f-8f24-601a67ea4d4e.png)

but still not follwing the templated suggested in comment on Feb 8, it was suggested to follow the same pattern that in #303.

Closed but created a new ticket for name improvement.

New ticket in clickup internal tracker to have this change done in v2.3.
