### ISSUE TITLE
source and sex are displayed as [object Object] in Family grid (in Family browser and in overview tab in interpretation manager)

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#396]
## Describe the bug

- [x] (1) Source values in the family members grid in the case interpreter overview are displayed as [object Object]

![image](https://user-images.githubusercontent.com/167875/152522903-3aec9091-c9ff-4af4-a18f-30ceec6ab91c.png)

- [x] (2) Sex in family browser is [object Object]

![image](https://user-images.githubusercontent.com/167875/152522974-d52a8fc5-9944-4e3d-a06f-292d7f9bfe5d.png)

## How to reproduce

- with user demouser study Ashkenazim Trio
(1)
- Select a case with a family
- In case interpreter select tab "Overview"
- In section Family, in the grid members, expand an individual
    
![image](https://user-images.githubusercontent.com/167875/152524960-a0443ce2-f060-470a-9396-b5d3ea33ec1b.png)

(2)
- From any application, in the header, select catalog/family_browser
- Expand a family row

**Comment by jmjuanes** [comment]
Fixed source values in family members grid in commit 5491d41 (in the screenshot the source is not provided, so a `-` character is displayed):

![image](https://user-images.githubusercontent.com/5751201/153579882-bf03d5b3-7c5c-45ec-8156-6025eadacb1d.png)

**Comment by jmjuanes** [comment]
Fixed displaying sex field in family grid in commit fedbc59:

![image](https://user-images.githubusercontent.com/5751201/153582236-d323393a-effc-474b-85f3-08173a4d1632.png)

**Comment by pamag** [comment]
## Review

commit IVA: 6df12c6cdc47629a3b362fe8150c53debfb501e2
commit OpenCGA: bcbe75e68198a1171ad977e747189ddcdbc74c39

FIXED
