### ISSUE TITLE
Variant-type-filter sends [object Object] to active filters

### ISSUE THREAD

**Issue by antonioaltamura** [opencb/jsorolla#404]
When you click on "Select All" in `variant-type-filter` you can see `opencga-active-filters` having a list of [object Object] at the field `type`. That happens because the list of variant types defined in `this._config.types` in some custom app configurations is an array of objects as `checkbox-field-filter` supports both array of strings and array of objects.

Also, it would be nice to have a "toggle" button instead of "Select all" (see https://github.com/opencb/jsorolla/issues/405).

![varianttype](https://user-images.githubusercontent.com/6325475/154057708-94910d6e-b9d0-48a6-89d8-607cc4083540.gif)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        4947bd62b3bed373d7adac94c45d365bdce59c56
    IVA commit:
        8ddfb063a7a144035504933ad94e807ba2e5e4ae

FIXED
