### ISSUE TITLE
Unable to delete filters right after being saved

### ISSUE THREAD

**Issue by antonioaltamura** [opencb/jsorolla#409]
The rubbish bin icon doesn't appear when you save a filter. To see that you have to force a refresh of the browser.

![filters1](https://user-images.githubusercontent.com/6325475/154268660-a83361ee-d31b-4bdf-80cb-4930ff92f1ee.gif)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit: bcbe75e68198a1171ad977e747189ddcdbc74c39
    IVA commit: 067443205dc02f14153103605b03174616683ded

FIXED
