### ISSUE TITLE
Save filters list doesn't update after deleting a filter

### ISSUE THREAD

**Issue by antonioaltamura** [opencb/jsorolla#410]
When you delete a filter, the list in the dropdown doesn't update right after, therefore it shows the deleted filter.

![filters2](https://user-images.githubusercontent.com/6325475/154269165-5580eef4-5828-4407-aa6d-4a9626cd73d5.gif)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit: bcbe75e68198a1171ad977e747189ddcdbc74c39
    IVA commit: 067443205dc02f14153103605b03174616683ded

FIXED

**Comment by pamag** [comment]
## Reviewed

Now it works but needs some improvements in the way events are managed.

[ ] Close ticket but open a new one for review active filter events and code.
