### ISSUE TITLE
Empty sections in Variant Browser Settings

### ISSUE THREAD

**Issue by jmjuanes** [opencb/jsorolla#413]
## Describe the bug

In the Variant Browser settings modal, the **Sample Genotype** section is hidden but a pill with this section title is displayed.

## To Reproduce

1. Go to Variant Browser.
2. Click on **Settings** button.
3. Click on **Sample Genotype** pill.

## Expected behavior

Empty or hidden sections should be removed from tabs and pills.

## Screenshots

![image](https://user-images.githubusercontent.com/5751201/154458443-190e7cd0-210a-4f59-af03-7b1b01be56ba.png)

## Additional context

This issue is related with #371.

**Comment by jmjuanes** [comment]
Fixed in commit 2232797: empty sections are hidden from tabs or pills on Variant Browser:

![image](https://user-images.githubusercontent.com/5751201/154462837-fc483e11-8e8a-4595-a6fd-3521fe008795.png)

In the Sample Variant Browser the **Sample Genotypes** setting pill is displayed as expected: 

![image](https://user-images.githubusercontent.com/5751201/154463310-f1d1edfc-8d37-4a82-a49b-3a20973808c8.png)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit: bcbe75e68198a1171ad977e747189ddcdbc74c39
    IVA commit: 1dfdef8b5ea4365a40f871bed8752016628b710f


FIXED
