### ISSUE TITLE
GO and HPO autocomplete data source issue

### ISSUE THREAD

**Issue by antonioaltamura** [opencb/jsorolla#415]
Term suggestions in GO and HPO filters don't work anymore due to a problem with the data source.

![Screenshot from 2022-02-17 13-10-55](https://user-images.githubusercontent.com/6325475/154479377-5d2794b2-cfd4-47b1-80b3-d6b38ec8d084.png)

**Comment by imedina** [comment]
@antonioaltamura There is an alternative solution to this, which is more homogeneous with the rest of JSorolla components, it could be interesting to explore it
