### ISSUE TITLE
Autocomplete filter default config

### ISSUE THREAD

**Issue by antonioaltamura** [opencb/jsorolla#417]
For the sake of consistency, all autocomplete filters with similar purpose should have the same basic config.
It seems `individual-id-autocomplete` default config has been changed to have `multiple` flag set to `false`.
https://github.com/opencb/jsorolla/blob/1dfdef8b5ea4365a40f871bed8752016628b710f/src/webcomponents/commons/filters/individual-id-autocomplete.js#L56
![IVA-v2-2-0-dev_individual](https://user-images.githubusercontent.com/6325475/154500866-03214602-f535-4d29-99cf-9c8081656217.png)

**Comment by pamag** [comment]
## Reviewed
