### ISSUE TITLE
Deleteriousness filters emit null value

### ISSUE THREAD

**Issue by antonioaltamura** [opencb/jsorolla#418]
If you deselect the key (score|tolerated|deleterious) in Protein Substitution Score filters they emit a `null` value.

![deleteriousness](https://user-images.githubusercontent.com/6325475/154531073-c567b7c9-0be3-4024-8884-8301bb690eed.gif)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        4947bd62b3bed373d7adac94c45d365bdce59c56
    IVA commit:
        8ddfb063a7a144035504933ad94e807ba2e5e4ae

FIXED
