### ISSUE TITLE
variant-file-info-filter caller Id overflow

### ISSUE THREAD

**Issue by antonioaltamura** [opencb/jsorolla#432]
In case the caller has an id too long, it overflows in `variant-file-info-filter` as in the screenshot.
![caller](https://user-images.githubusercontent.com/6325475/158568131-c7e33c59-ee37-4208-afd6-7f4292f1d3d7.png)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        4947bd62b3bed373d7adac94c45d365bdce59c56
    IVA commit:
        7e2958f01bf37ba12d53de307abdb57511040533

MERGED

This issue is resolved in PR #439 
![image](https://user-images.githubusercontent.com/167875/160357937-81f49496-bbcb-4d36-9a29-7d771ec7b117.png)
