### ISSUE TITLE
Family Browser grid toolbar bug

### ISSUE THREAD

**Issue by antonioaltamura** [opencb/jsorolla#447]
The configuration in Family Browser is not correctly applied to `opencb-grid-toolbar` and as a consequence, the toolbar is not shown. See recording.

**To Reproduce**
1. Go to Variant Analysis => Catalog => Family Browser
2. the toolbar won't be there, because `toolbarConfig` in `family-grid.js` is not correctly passed to `opencb-grid-toolbar.js`
3. Switch study
4. Observe how refreshing `family-grid` fixes the problem

![family](https://user-images.githubusercontent.com/6325475/159490500-b25527ac-873f-4bd8-a26a-88f18a443a3e.gif)

**Comment by halender** [comment]
@pamag . Can you check it, please? PR is already reviewed. https://github.com/opencb/jsorolla/pull/449

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        4947bd62b3bed373d7adac94c45d365bdce59c56
    IVA commit:
        8ddfb063a7a144035504933ad94e807ba2e5e4ae

FIXED
