### ISSUE TITLE
select-token-filter duplicates the tag on tag insert 

### ISSUE THREAD

**Issue by antonioaltamura** [opencb/jsorolla#448]
As you select an element from the dropdown, it will be added twice in the filter field.

**To Reproduce**
1. Go to Variant Analysis => Catalog => Family Browser
2. Select an id in the Family ID filter

![familyidfilter](https://user-images.githubusercontent.com/6325475/159492014-a6ef1ded-568c-4159-a0ec-9564696ed545.gif)

**Comment by Rodielm** [comment]
Fixed:[8ddfb06](https://github.com/opencb/jsorolla/commit/8ddfb063a7a144035504933ad94e807ba2e5e4ae)
![FamilyFixedTag](https://user-images.githubusercontent.com/10471758/159684830-0259df97-4f4d-418a-9783-b1dfd9b8d3a5.gif)

**Comment by pamag** [comment]
## Reviewed
    OpenCGA commit:
        4947bd62b3bed373d7adac94c45d365bdce59c56
    IVA commit:
        8ddfb063a7a144035504933ad94e807ba2e5e4ae

FIXED
