### ISSUE TITLE
bug: Content-type parsing

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/jsorolla#58]
[cellbase-manager.js#L52](https://github.com/opencb/jsorolla/blob/develop/src/core/cellbase-manager.js#L52) doesn't parse Content-Type header properly when it has a parameter, `Content-Type: application/json;charset=utf-8` for examle:

```
            var contentType = this.getResponseHeader('Content-Type');
            if (contentType === 'application/json') {
```

The header is defined in [RFC1314](https://tools.ietf.org/html/rfc1341) as: 
```
            Content-Type := type "/" subtype *[";" parameter]
```

**Comment by mbsimonovic** [comment]
there're a few places where a code like this exists, and in the [rest-client.js](https://github.com/opencb/jsorolla/blob/e5bafb9f795aa741bb0dbb8ca9ef4523f7c7dc51/src/core/clients/rest-client.js#L76) you actually fixed it:
```
                    // startsWith() is used because sometimes the contentType is 'application/json;charset=utf-8'
                    if (contentType.startsWith("application/json")) {
```

ps. perhaps it's safer to go with indexOf, since not all browsers support startsWith.

**Comment by agaor** [comment]
thanks for your contribution mbsimonovic. The code is changed.
