### ISSUE TITLE
Tracks in genome maps are not rendered anymore in firefox

### ISSUE THREAD

**Issue by jmmut** [opencb/jsorolla#9]
Chrome does render them, but firefox (at least 33.0) doesn't.

In branch feature/opencga-0.3, last commit working is 77540032fa4ed423b4172c35c170d8fa51e11c5c

**Comment by imedina** [comment]
What is the status of this issue?

**Comment by imedina** [comment]
What's the status of this issue?

**Comment by agaor** [comment]
Thanks to the browser updates, genome maps are rendered correctly in Firefox.
